import { Product } from '../products';

export const brandAnuaProducts: Product[] = [
  {
    id: 8995681272044,
    brand: "ANUA",
    name: "ANUA Heartleaf Centella Red Spot Cream (30g)",
    category: "Moisturizers",
    price: 21.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/ANUA_Heartleaf_Centella_Red_Spot_Cream_30g.png?v=1772983941",
    description: "A spot treatment that helps treat red spots, with a mild, non-sticky formula. ANUA Heartleaf Centella Red Spot Cream formulated with Houttuynia Cordata flower/leaf/stem water, with anti-inflammatory properties, to soothe irritated skin, balance sebum secretion, and treat acne and pimples. Blended with a complex of ceramides, it also helps to maintain water and oil balance, enhance hydration, and facilitate the recovery of tired skin. The thin soothing coating film wraps the skin once, and as you spread it, moisture bursts out for a refreshing finish. Features Strengthens the skin barrier and provides deep moisture E ffective against redness and breakouts Care for broken skin barrier with 6 types of ceramide Fluidrop™ technology for soothing to penetrate deeper and faster Skin Concerns Redness &amp; Irritation Dryness Rough Skin Acne &amp; Blemishes Skin Types Ideal for acne-prone and sensitive skin . Made In South Korea How to use As the last step of your skincare routine, apply a moderate amount to the skin and gently massage to aid absorption. Apply a layer on tired spots for better results. Ingredients Key Highlights Houttuynia Cordata : Anti-inflammatory properties to calm and soothe irritated skin, while balancing sebum and managing acne and breakouts Madecassoside &amp; Asiatic Acid : Amplify soothing effects, while helping to improve skin elasticity. Centella Asiatica (Cica) Extract : K nown for its soothing, anti-inflammatory, and healing properties , which help reduce redness, relieve irritation, and promote rapid skin recovery. Ceramides : Maintain water-oil balance, boost hydration and facilitate troubled skin recovery. Niacinamide : Fades pigmentation. Ingredient Highlights Paraben-Free Sulfate-Free Mineral Oil-Free Fragrance-Free Alcohol-Free",
    ingredients: "Full list of ingredients Water, Houttuynia Cordata Flower/Leaf/Stem Water, Glycerin, Butylene Glycol, Panthenol, 2,3-Butanediol, Dicaprylyl Carbonate, Methyl Trimethicone, Niacinamide, 1,2-Hexanediol, Pentylene Glycol, Squalane, Cetearyl Olivate, Sorbitan Olivate, Sorbitol, Diphenylsiloxy Phenyl Trimethicone, Sucrose Polystearate, Hydrogenated Polyisobutene, Poly C10-30 Alkyl Acrylate, Stearyl Dimethicone, Cetyl Palmitate, Cetearyl Alcohol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Polyglyceryl-3 Distearate, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl, Taurate Copolymer, Hydrogenated Olive Oil Decyl Esters, Sorbitan Palmitate, Aminomethyl Propanediol, Glyceryl Stearate, Sodium Acrylate/Sodium Acryloyldimethyl, Taurate Copolymer, Polyisobutene, Polyglyceryl-6 Caprylate, Hydrogenated Lecithin, Cellulose, Ethylhexylglycerin, Polyglyceryl-4 Caprate, Adenosine, Candida Bombicola/Glucose/Methyl, Rapeseedate Ferment, Olea Europaea (Olive) Oil Unsaponifiables, Sodium Phytate, Sorbitan Isostearate, Glyceryl Stearate Citrate, Beta-Sitosterol, Melia Azadirachta Leaf Extract, Allantoin, Melia Azadirachta Flower Extract, Caprylyl/Capryl Glucoside, Sorbitan Oleate, Madecassic Acid, Ocimum Sanctum Leaf Extract, Asiaticoside, Madecassoside, Macadamia Ternifolia Seed Oil, Phytosterols, Curcuma Longa (Turmeric) Root Extract, Stearic Acid, Corallina Officinalis Extract, Asiatic Acid, Tocopherol, Ceramide NP, Cholesterol, Phytosphingosine, Ceramide NG, Ceramide NS, Ceramide AP, Ceramide AS, Ceramide Eop.",
    reviews: []
  },
  {
    id: 8933180276972,
    brand: "ANUA",
    name: "ANUA Airy Sun Cream SPF 50+ PA++++ (50ml)",
    category: "Sun Care",
    price: 32.00,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/ANUA_Airy_Sun_Cream_SPF_50_PA_50ml.png?v=1772983546",
    description: "A physical UV filter that provides maximum protection against UVA and UVB rays ANUA Airy Sun Cream SPF 50+ PA++++ is a broad-spectrum sunscreen designed for sensitive skin. This physical sun cream uses powder dispersion technology to create a smooth, dewy texture that leaves no white cast and provides a supple finish. Formulated with Centella Asiatica, Houttuynia Cordata, Tea Tree and Artemisia Capillaris Extract, to soothe and protect by reducing redness, irritation and discomfort. Features SPF50+/PA++++ mineral sunscreen Provides long-lasting protection even in wet conditions Contains that help maintain skin moisture Lightweight and acts against redness Helps regulate sebum secretion, preventing oily skin Skin Concerns Redness &amp; Irritation Anti-Aging Dark Spots Skin Types Suitable for all skin types including sensitive skin NPN 80139753 Made In SOUTH KOREA 🇰🇷 How to use Apply as the last step of your skincare routine, 15 minutes before sun exposure. Apply a finger-sized amount to the skin, avoiding the eye and mouth areas. If necessary, reapply frequently. Ingredients Key Ingredients Centella Asiatica Extract : Soothing and has emollient properties tp help reduce redness, irritation, and discomfort. Heartleaf Extract (Houttuynia Cordata) : Nourishes and softens the skin while relieving irritation and i mproves skin texture. Tea Tree Extract &amp; Wormwood Extract (Artemisia Absinthium) : Anti-inflammatory and antibacterial. Hyaluronic Acid : Retains moisture in the skin, providing deep hydration and maintaining skin elasticity. Ingredient Highlights Vegan Cruelty Free Sulfate-Free Mineral Oil Free Paraben-Free Alcohol-Free Fragrance-Free",
    ingredients: "Full list of ingredients Water, Zinc Oxide, Cyclohexasiloxane, Butyloctyl Salicylate, Propanediol, Propylheptyl Caprylate, Isododecane, Polyglyceryl-3 Polydimethylsiloxyethyl Dimethicone, Caprylyl Methicone, Dicaprylyl Carbonate, Methyl Methacrylate Crosspolymer, Polymethylsilsesquioxane, Centella Asiatica Extract, Artemisia Capillaris Extract, Houttuynia Cordata Extract, Melaleuca Alternifolia Extract, Sodium Hyaluronate, Disteardimonium Hectorite, Magnesium Sulfate, Triethoxycaprylylsilane, 1,2-Hexanediol, Polyglyceryl-2 Dipolyhydroxystearate, Lauryl Polyglyceryl-3 Polydimethylsiloxyethyl Dimethicone, Phenyl Trimethicone, Acrylates/Dimethicone Copolymer, Glyceryl Caprylate, Caprylyl Glycol, Ethylhexylglycerin, Tocopherol, Butylene Glycol, Pentylene Glycol.",
    reviews: []
  },
  {
    id: 8755559891180,
    brand: "ANUA",
    name: "ANUA Azelaic Acid 10 Hyaluron Soothing Serum (30ml)",
    category: "Serums",
    price: 29.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/ANUA-43-01_1.webp?v=1766074516",
    description: "Transform your skincare routine with the ANUA Azelaic Acid 10+ Hyaluron Serum, a daily calming serum designed to brighten, hydrate, and strengthen your skin. Enriched with 10% Azelaic Acid and a nourishing blend of , this serum offers an all-in-one solution for evening out skin tone, reducing blemishes and redness, and diminishing fine lines. Not only does it provide long-lasting hydration and protection, but it also brightens and evens skin tone with the help of Azelaic Acid, which minimizes discoloration and promotes a radiant complexion. Additionally, Centella Asiatica and Green Tea Leaf Water work in harmony to soothe irritation and strengthen the skin barrier, while Zinc PCA targets breakouts and excess oil, leaving skin clear and refreshed. For dryness-prone and sensitive skin, this serum calms redness and inflammation, supporting the skin's natural repair process. To top it off, Hyaluronic Acid, Ceramide, and Squalane deeply hydrate and improve skin elasticity, leaving it smooth, supple, and resilient. Features Brightens &amp; Evens Skin Tone Calms &amp; Soothes Reduces Redness &amp; Inflammation Targets Breakouts &amp; Excess Oil Hydrates &amp; Strengthens Skin Concerns Uneven skin tone Redness &amp; Irritation Acne Dehydrated skin Skin Types Suitable for all skin types, including sensitive skin Made In South Korea How to use After your cleansing and toning steps, dispense 2-3 pumps and spread evenly onto the face. You can layer on extra over inflamed or red areas. Pat gently to help with absorption and follow with a moisturizer. Ingredients Hero Ingredients Azelaic Acid (10%) : Brightens, smooths, and improves skin texture while addressing blemishes and uneven tone. Centella Asiatica : Soothes irritation, replenishes hydration, and strengthens the skin barrier for optimal healing. Green Tea Leaf Water : Packed with antioxidants, it calms and protects the skin from environmental stressors. Zinc PCA : Targets acne and inflammation while reducing sebum production and accelerating skin recovery. Hyaluronic Acid, Ceramide &amp; Squalane : Deliver intense hydration, improve elasticity, and restore the skin’s natural barrier. Ingredient Highlights Cruelty-Free Sulfate-Free Paraben-Free Silicone-Free Mineral Oil Free Alcohol-Free",
    ingredients: "Full list of ingredients Aqua (Water), Azelaic Acid, Propylene Glycol, Sodium Hydroxide, Dipropylene Glycol, 1,2-Hexanediol, Panthenol, Hydroxyethylcellulose, Betine Salicylate, Glycerin, Biosaccharide Gum-1, Ethylhexylglycerin, Allantoin, Dipotassium Glycyrrhizate, Melia Azadirachta Leaf Extract, Camellia Sinensis Leaf Water, Sodium Hyaluronate, Melia Azadirachta Flower Extract, Niacinamide, Aloe Barbadensis Leaf Juice, Beta-Glucan, Centella Asiatica Extract, Centella Asiatica Leaf Extract, Centella Asiatica Root Extract, Asiatic Acid, Asiaticoside, Madecassic Acid, Madecassoside, Squalane, Zinc PCA, Butylene Glycol, Pentylene Glycol, Caprylyl/Caprul Glucoside, Hydrogenated Lecithin, Ceramide NP",
    reviews: []
  },
  {
    id: 8716254773484,
    brand: "ANUA",
    name: "ANUA Peach Niacin Serum Mask",
    category: "Masks",
    price: 3.98,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/ANUA_Peach_Niacin_Serum_Mask.png?v=1772984285",
    description: "A brightening sheet mask for instant and long-term glass skin appearance. ANUA Peach Niacin Serum Mask is soaked in ANUA's Peach 70 Niacin Serum, promising to fade pigmentation, revitalize the skin texture, and deliver glass skin. It is enriched with 70% Peach Fruit Extract and 2% Niacinamide, plus key like vitamin B12, hyaluronic acid, and Fermented Yeast Extract (soothing, nourishing). The sheet mask adheres perfectly to the skin, allowing the serum to penetrate into the skin and deliver a soft, radiant complexion. Features Sheet masked soaked in ANUA's Peach 70 Niacin Serum Soothing, nourishing Fades hyperpigmentation Deeply hydrating Skin Concerns Dehydrated Skin Hyperpigmentation Dullness Skin Types Suitable for all skin types Made In South Korea How to use Use after cleansing &amp; toning. Remove sheet mask from packaging and carefully fit mask over the face. Remove after 15-20 minutes. Gently tap remaining essence on the skin to enhance absorption. Ingredients Key Highlights Niacinamide Peach Fruit Extract Hyaluronic Acid Panthenol Ingredient Highlights Alcohol-Free Mineral-Oil Free Paraben-Free Silicone-Free",
    ingredients: "Full list of ingredients Prunus Persica (Peach) Fruit Extract(70%), Water, Glycerin, Methylpropanediol, Niacinamide, 1,2-Hexanediol, Lactobacillus Ferment, Phellinus Linteus Extract, Vincetoxicum Atratum Extract, Hydrolyzed Hyaluronic Acid, Althea Rosea Flower Extract, Camellia Sinensis Seed Oil, Yeast Ferment Extract, Safflower Seed Oil, Salvia Hispanica Seed Oil, Prunus Persica (Peach) Flower Extract, Candida Bombicola/Glucose/Methyl Rapeseedate Ferment, Hyaluronic Acid, Sodium Hyaluronate, Hydroxyacetophenone, Polypropanediol, Butylene Glycol, Allantoin, Tromethamine, Polyglyceryl-10 Isostearate, Polyglyceryl-10 Oleate, Sodium Phytate, Cyanocobalamin, Ethylhexylglycerin, Panthenol, Caprylic/Capric Triglyceride, Betaine Salicylate, Hydrogenated Lecithin, Linoleic Acid, Linolenic Acid, Sucrose Palmitate, Ceramide NP, Carbomer, Fragrance",
    reviews: []
  },
  {
    id: 8716302516460,
    brand: "ANUA",
    name: "ANUA Heartleaf 87 Low pH Deep Cleansing Water (500g)",
    category: "Cleansers",
    price: 22.00,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Product_Images_90_a9406654-4d10-4d2f-b157-240a6edca7c9.png?v=1769082342",
    description: "The ultimate solution for gentle yet effective makeup removal. Anua Heartleaf 87 Low pH Deep Cleansing Water uses advanced micellar technology to ensure deep cleansing and full makeup removal. This gentle, low pH formula features Houttuynia Cordata (Heartleaf) Extract, renowned for its skin-friendly properties, as well as plant-derived squalane and panthenol (moisturizing ). Skin will be left cleansed and moisturized, with no tight feeling. Features Mildly acidic (low pH) formula doesn't irritate the skin Removes makeup without harsh scrubbing Fluid Micellar System deeply cleanses the pores Soothing and moisturizing No post-cleansing tightness Skin Concerns Irritation Skin Types Suitable for all skin types, including sensitive skin Made In South Korea How to use Saturate a cotton pad thoroughly Gently wipe from the inside to the outside of the face Optional to double cleanse with a foaming cleanser For coloured or waterproof makeup, press and hold for 5 seconds before wiping. Ingredients Key Highlights H outtuynia Cordata Extract Squalane Panthenol Ingredient Highlights Cruelty-Free &amp; Vegan Alcohol-Free Oil-Free Paraben-Free Sulfate-Free Silicone-Free Fragrance-Free",
    ingredients: "Full list of ingredients Purified Water, Propanediol, Polyglyceryl-4 Caprate, 1,2-Hexanediol, Dipropylene Glycol, Houttuynia Cordata Extract (1,100 ppm), Panthenol, Ethylhexylglycerin, Citric Acid, Sodium Citrate, Squalane, Tocopherol",
    reviews: []
  },
  {
    id: 8585797894380,
    brand: "ANUA",
    name: "ANUA Rice 70 Glow Milky Toner (250ml)",
    category: "Toners",
    price: 24.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/processed_cmd0t3j2g04qan5u6o2xp93my_1752359403622.png?v=1752359408",
    description: "A lightweight milky toner that brightens and moisturizes, revealing glass skin. ANUA Rice 70 Glow Milky Toner is formulated with a blend of rice water, niacinamide, and ceramides to brighten the skin and moisturize deep down. It helps to repair the natural moisture barrier. This non-comedogenic, fragrance-free formula is suitable for all skin types and can be used everyday. Features Non-sticky, lightweight milky toner Moisturizing and brightening Rice Cera-Protein (blend of ceramides and protein) strengthens the skin barrier Skin Concerns Dehydrated Skin Dullness Rough skin Skin Types All skin types Specifically dry, sensitive skin Made In South Korea How to use Apply an appropriate amount on cleansed skin and pat into the skin for absorption or apply to cotton pad and wipe across cleansed skin. Tip: Soak a cotton pad and leave on skin for 10-15 minutes before applying makeup for extra moisture. Key Ingredients 70% Rice Water+: Helps improve skin clarity and balance, making skin look more radiant and balanced with regular use. Niacinamide: This versatile ingredient helps moisturize the skin, leaving the complexion radiant and provides gentle texture care. Ceramide: Helps maintain the skin’s moisture barrier. Ingredient Highlights Alcohol-Free Mineral-Oil Free Paraben-Free Sulfate-Free Fragrance-Free",
    ingredients: "Full list of ingredients Oryza Sativa (Rice) Bran Water(71%). Butylene Glycol, Glycerin, Dipropylene Glycol, Niacinamide, Propanediol, Water, 1,2-Hexanediol, Methyl Gluceth-20, Panthenol, Betaine, Oryza Sativa (Rice) Extract(3,753ppm), Hydroxyacetophenone, Diphenyl Dime thicone, Triethylhexanoin, Hydrogenated Lecithin, Adenosine, Ethylhexylglycerin, Carbomer, Tromethamine, Xanthan Gum, Glyceryl Acrylate/Acrylic Acid Copolymer, Theobroma Cacao (Cocoa Seed Extract, Sodium Hyaluronate, Hydrolyzed Hyai uronic Acid, Hyaluronic Acid, Dextrin, Hydrolyzed Rice Protein (3,000ppb), Oryza Sativa (Rice) Seed Protein(3,000ppb), Ceramide NP, Sodium Lauroyl Lactylate, Arbutin, Ascorbic Acid, Allantoin, Ceramide AP, Phytosphingosine, Cholesterol, Ceramide EOP This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 8493012877548,
    brand: "ANUA",
    name: "ANUA Heartleaf 70% Soothing Cream (100ml)",
    category: "Moisturizers",
    price: 28.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/ANUA_Heartleaf_70__Soothing_Cream__100m_PNG.png?v=1769695652",
    description: "A lightweight, soothing gel cream formulated with 70% Heartleaf Extract. ANUA Heartleaf 70% Soothing Cream addresses skin inflammation, reduces redness, and soothes the skin. In addition to 700,000ppm Heartleaf, it also contains panthenol, hyaluronic acid, and betaine to keep the skin hydrated and plump. Centella Asiatica Extract, Madecassic Acid, Asiaticoside, and Asiatic Acid are key that supplement the cream's soothing effects. Features Soothes inflammation and reduces redness Lightweight gel cream Refreshing feeling upon application Skin Concerns Redness &amp; Irritation Dehydrated Skin Skin Types Normal skin types, including sensitive skin Made In South Korea How to use At the last step of skincare routine (before sunscreen), take an adequate amount and gently massage onto skin until absorbed. Ingredients Ingredient Highlights Alcohol-Free Mineral-Oil Free Paraben-Free Sulfate-Free",
    ingredients: "Full list of ingredients Houttuynia Cordata Extract (70%), Butylene Glycol, Glycerin, Isoamyl, Laurate, Water, Pentylene Glycol, 1,2-Hexanediol, Centella Asiatica Extract, Portulaca Oleracea Extract, Betaine, Madecassic Acid, Asiatic Acid, Asiaticoside, Chlorella Vulgaris Extract, Panthenol, Ethylhexylglycerin, Hydrogenated Polydecene, Glucose, Niacinamide, Vinyl Dimethicone, Caprylyl Methicone, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Dimethiconol, Polymethylsilsesquioxane, Glyceryl Acrylate/Acrylic Acid Copolymer, Tromethamine, Ammonium Acryloyldimethyltaurate/VP Copolymer, Fructooligosaccharides, Fructose, Dipotassium Glycyrrhizate, Sodium Phytate, Dipropylene Glycol, Tocopherol, Xanthan Gum Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 7964008579308,
    brand: "ANUA",
    name: "ANUA Heartleaf Pore Control Cleansing Oil (200ml)",
    category: "Cleansers",
    price: 26.00,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/anua_3.png?v=1752361023",
    description: "Melt away blackheads, whiteheads, sebum and impurities! ANUA Heartleaf Pore Control Cleansing Oil is the first step to glass skin! This hypoallergenic and non-comedogenic cleansing oil easily dissolves all impurities on the skin including sunscreen, makeup, blackheads, whiteheads and other impurities that may clog your pores. With heartleaf extract, it also soothes irritated skin and is suitable for sensitive and acne-prone skin. After 4 weeks of use, studies have shown a significant decrease in blackheads, whiteheads, acne (papule and pustules), oil and sebum production. Features Vegan and cruelty free Non-comedogenic, hypoallergenic Easily dissolves sunscreen, foundation and eye makeup Melts blackheads, whiteheads and sebum in pores Rinses off without residue Skin Concerns Clogged Pores/ Blackheads Acne Skin Types All skin types Mild version is good for sensitive skin Best for Acne-Prone Skin Made In South Korea How to use Take 2-3 pumps of cleansing oil on hands. Gently smooth and roll over face. Wet face to emulsify cleansing oil to remove blackheads. Rinse thoroughly with water. Key Highlights H outtuynia cordata extract Plant oils (sunflower, olive, jojoba, grape seed, macadamia seed) Ingredient Highlights Alcohol-Free Mineral-Oil Free Paraben-Free Sulfate-Free Silicone-Free Fragrance-Free (Mild version only)",
    ingredients: "Full list of ingredients [Regular] Ethylhexyl Palmitate, Sorbeth-30 Tetraoleate, Sorbitan Sesquioleate, Caprylic/Capric Triglyceride, Butyl Avocadate, Fragrance, Helianthus Annuus (Sunflower) Seed Oil, Macadamia Ternifolia Seed Oil, Olea Europaea (Olive) Fruit Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Vitis Vinifera (Grape) Seed Oil, Caprylyl Glycol, Ethylhexylglycerin, Curcuma Longa (Turmeric) Root Extract, Melia Azadirachta Flower Extract, Tocopherol, Melia Azadirachta Leaf Extract, Houttuynia Cordata Extract, Corallina Officinalis Extract, Melia Azadirachta Bark Extract, Moringa Oleifera Seed Oil, Ocimum Sanctum Leaf Extract [Mild] Ethylhexyl Stearate, Sorbeth-30 Tetraoleate, Cetyl Ethylhexanoate, Caprylic/Capric Triglyceride, Triethylhexanoin, Isododecane, Water, Rosmarinus Officinalis (Rosemary) Leaf Oil, Sorbitan Sesquioleate, Tocopherol, Helianthus Annuus (Sunflower) Seed Oil, Houttuynia Cordata Extract This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 8140955484396,
    brand: "ANUA",
    name: "ANUA Peach 70% Niacin Serum (30ml)",
    category: "Serums",
    price: 26.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/processed_cmd0t21in04pwn5u6utqmb6i8_1752359308889.png?v=1752359313",
    description: "For instant and long-term glass skin appearance! ANUA Peach 70% Niacin Serum is a facial serum to deliver glass skin instantly and over time. This peach serum helps to brighten dull skin, soften skin and even out skin tone and hyperpigmentation, I t contains 5% niacinamide for high efficacy and is derived from Vitamin B12+ which contributes to the natural pink colour. It also contains Desert Yeast Oil which is a powerful hydrating ingredient that can survive even in the driest deserts. Features Vegan and cruelty free Non-comedogenic, hypoallergenic Brightens and evens skin tone for glass skin delivery Quenches dryness using Desert Yeast Oil and 3 types of hyaluronic acid Skin Concerns Dullness Uneven skin Skin Types Normal and Dry Made In South Korea How to use Use after cleansing &amp; toning, up to twice daily. Always finish with sunscreen for daytime use. Smooth 2-3 drops over face &amp; neck and avoid eyes. A little goes a long way. Key Highlights 5% Niacinamide: Moisturizes the skin, leaving the complexion looking revitalized. Vitamin B12 + Triple Hyaluronic Acid + Desert Yeast Oil: Provides deep hydration with moisturizing ingredients. Natural pink color from VITAMIN B12 with no artificial coloring. Ingredient Highlights Alcohol-Free Mineral-Oil Free Paraben-Free Sulfate-Free Silicone-Free",
    ingredients: "Full list of ingredients Prunus Persica (Peach) Fruit Extract, Glycerin, Niacinamide, Butylene Glycol, Diethoxyethyl Succinate, Water, 1,2-Hexanediol, Lactobacillus Ferment, Sodium Hyaluronate, Sphingomonas Ferment Extract, Alpha-Arbutin, Melia Azadirachta Flower Extract, Ocimum Sanctum Leaf Extract, Melia Azadirachta Leaf Extract, Carthamus Tinctorius (Safflower) Seed Oil, Salvia Hispanica Seed Oil, Curcuma Longa (Turmeric) Root Extract, Corallina Officinalis Extract, Hydrolyzed Hyaluronic Acid, Chamaecyparis Obtusa Leaf Extract, Prunus Persica (Peach) Flower Extract, Centella Asiatica Extract, Artemisia Princeps Leaf Extract, Pentylene Glycol, Polyglyceryl-10 Laurate, Betaine Salicylate, Sodium Phytate, Cellulose, Caprylic/Capric Triglyceride, Hydrogenated Lecithin, Panthenol, Polyglutamic Acid, Linoleic Acid, Linolenic Acid, Polyglyceryl-10 Oleate, Sucrose Palmitate, Cyanocobalamin, 3-O-Ethyl Ascorbic Acid, Ceramide NP, Lactobionic Acid, Asiaticoside, Madecassic Acid, Asiatic Acid, Xanthan Gum, Fragrance(Parfum) This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 8141043171564,
    brand: "ANUA",
    name: "ANUA Heartleaf LHA Moisture Peeling Gel (120ml)",
    category: "Exfoliants",
    price: 21.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/lha_EDITED.png?v=1765403648",
    description: "Lift and roll your dead skin cells into little particles that easily wash off! ANUA Heartleaf LHA Moisture Peeling Gel is a hypoallergenic peeling gel that g ently sloughs off the dead skin cells without irritation and helps soothe the skin. It uses LHA (beta-lipohydroxy acid) which is well known for its gentle, non-irritating mode of exfoliation. The peeling gel binds with sebum and surface skin, rolling it into particles of dead skin that easily rinses away for a noticeable improvement in the overall texture and tone of the skin. Irritated and sensitive skin is also soothed by heartleaf extract, and the mild exfoliating gel takes care of dead cells and sebum. Features Vegan and cruelty free Non-comedogenic, hypoallergenic Soothes irritated and sensitive skin with heartleaf extract Gently lifts and binds dead skin cells into particles that wash off Reveals clean, smooth skin with improved texture Skin Concerns Rough Skin Skin Types All skin types Made In South Korea How to use After cleansing, apply a proper amount of peeling gel to wet skin, avoiding the eye and lip areas. Gently massage it within a minute and rinse off with lukewarm water Key Highlights LHA: A milder alternative of Salicylic Acid that effectively removes excess sebum deep within the pores Cellulose: Draws out dead skin cells to gently exfoliate the skin's surface. Hyaluronic Acid: Keeps the skin hydrated and helps maintain its natural moisture barrier. Houttuynia Cordata Extract (10,000ppm) Ingredient Highlights Alcohol-Free Mineral-Oil Free Paraben-Free Sulfate-Free Silicone-Free Fragrance-Free",
    ingredients: "Full list of ingredients Water, Dipropylene Glycol, Cellulose, 1,2-Hexanediol, Arginine, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Propanediol, Allantoin, Carthamus Tinctorius (Safflower) Flower Extract, Dextrin, Polyglyceryl-10 Laurate, Gardenia Jasminoides Fruit Extract, Disodium EDTA, Theobroma Cacao (Cocoa) Extract, Glycerin,Houttuynia cordata Extract, Aloe Ferox Leaf Extract, Bioflavonoids, Sodium Hyaluronate, Caprylyl Glycol, Capryloyl Salicylic Acid, Brassica Oleracea Italica (Broccoli) Extract, Ethylhexylglycerin This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 8204922290412,
    brand: "ANUA",
    name: "ANUA Niacinamide 10% + TXA 4% Dark Spot Correcting Serum (30ml)",
    category: "Serums",
    price: 27.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Anua_Niacinamide_10_TXA_4_Kiyoko_Beauty.png?v=1771503079",
    description: "A lightweight, fragrance-free serum that fades dark spots to promote a brighter complexion. ANUA Niacinamide 10% + TXA 4% Dark Spot Correcting Serum is formulated with 3 powerful brightening 10% Niacinamide, 4% Tranexamic Acid, and 2% Arbutin . Together, the ingredients work to fade dark spots including acne scars and hyperpigmentation. It is a lightweight, fragrance free serum packed also with Hyaluronic Acid and Ceramides to hydrate and strengthen the skin barrier at the same time. Features Fades stubborn dark spots Lightweight serum Promotes healthy skin barrier Skin Concerns Hyperpigmentation Uneven skin Dullness Skin Types All skin types, including acne-prone and sensitive skin Made In South Korea How to use After toner, apply 2-3 drops onto the skin and gently pat until absorbed. Make sure to apply sunscreen after when used in the morning. Ingredients Key Ingredients 10% Niacinamide: It helps improve the appearance of clearer, more balanced skin, as well as smoothness 4% TXA: This ingredient helps skin looks more radiant and balanced. 2% Arbutin: This gentle ingredient helps improve the appearance of skin clarity and balance, while subtly encouraging the skin’s natural radiance with regular use. Ingredient Highlights Cruelty-Free Alcohol-Free Paraben-Free Sulfate-Free Silicone-Free Fragrance-Free",
    ingredients: "Full list of ingredients Water, Glycerin, Niacinamide, Tranexamic Acid, Butylene Glycol, Diethoxyethyl Succinate, 1,2-Hexanediol, Arbutin, Sodium Hyaluronate, Alpha-Arbutin, Coccinia Indica Fruit Extract, Eclipta Prostrata Extract, Macadamia Integrifolia Seed Oil, Olea Europaea (Olive) Fruit Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Vitis Vinifera (Grape) Seed Oil, Theobroma Cacao (Cocoa) Extract, Hydrolyzed Hyaluronic Acid, Chamaecyparis Obtusa Leaf Extract, Prunus Persica (Peach) Flower Extract, Camellia Sinensis Seed Oil, Yeast Ferment Extract, Centella Asiatica Extract, Artemisia Princeps Leaf Extract, Candida Bombicola/Glucose/Methyl Rapeseedate Ferment, Hyaluronic Acid, Pentylene Glycol, Betaine Salicylate, Sucrose Palmitate, Hydrogenated Lecithin, Gellan Gum, Sodium Phytate, Cellulose, Caprylic/Capric Triglyceride, Panthenol, Cyanocobalamin, Polyglutamic Acid, 3-0-Ethyl Ascorbic Acid, Ceramide NP, Dextrin, Asiaticoside, Madecassic Acid, Asiatic Acid, Dimethylsilanol Hyaluronate, Hydrolyzed Sodium Hyaluronate, Potassium Hyaluronate, Hydroxypropyltrimonium Hyaluronate, Sodium Hyaluronate Crosspolymer, Sodium Hyaluronate Dimethylsilanol, Sodium Acetylated Hyaluronate, Xanthan Gum *Ingredients may change at manufacturer's discretion. For the most accurate and up-to-date ingredients list, please refer to the product packaging.",
    reviews: []
  },
  {
    id: 8148536590572,
    brand: "ANUA",
    name: "ANUA Heartleaf 77% Soothing Sheet Mask",
    category: "Masks",
    price: 3.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/anua-us-sheet-mask-10ea-heartleaf-77-soothing-sheet-mask-1161173116.png?v=1754147915",
    description: "Harness the power of heartleaf for troubled skin. ANUA Heartleaf 77% Soothing Sheet Mask is formulated with 77% heartleaf extracts to deeply soothe sensitive skin and repair damaged skin barrier. It maximizes moisture retention and helps to reduce redness from irritation and acne. With soft, microfiber sheets, it gently adheres to the skin and can be used daily without irritating the skin. Features Vegan and cruelty free Non-comedogenic, hypoallergenic Natural, microfiber sheet derived from plant extracts Calms and soothes irritated and red skin Hydrates and strengthens skin barrier Skin Concerns Dehydrated Skin Redness &amp; Irritation Acne Skin Types Normal skin types Made In South Korea How to use After cleansing, place the mask sheet on the face avoiding lip and eye areas and leave on for 15-20 minutes. Apply the excess product all over your face and skin. Key Highlights Houttuynia Cordata Extract (77%) Ingredient Highlights Alcohol-Free Mineral-Oil Free Paraben-Free Sulfate-Free Silicone-Free Fragrance-Free",
    ingredients: "Full list of ingredients Houttuynia Cordata Flower/Leaf/Stem Water, Glycerin, Water, Dipropylene Glycol, Glycereth-26, 1,2-Hexanediol, Propanediol, Arginine, Allantoin, Carbomer, Polyglyceryl-4 Caprate, Xanthan Gum, Ethylhexylglycerin, Disodium EDTA, Butylene Glycol, Sodium Hyaluronate, Polyglyceryl-10 Laurate, Polyglyceryl-10 Myristate, Squalane, Butyrospermum Parkii (Shea) Butter, Hydrogenated Lecithin, Illicium Verum (Anise) Fruit Extract, Octyldodecanol, Hamamelis Virginiana (Witch Hazel) Extract, Glyceryl Citrate/Lactate/Linoleate/Oleate, Glyceryl Oleate, Oleyl Alcohol, Ceramide NP, Centella Asiatica Extract, Glycolipids, Glycosphingolipids, Hippophae Rhamnoides Fruit Extract, Olea Europaea (Olive) Fruit Oil, Tocopherol, Chamomilla Recutita (Matricaria) Flower Extract, Candida Bombicola/Glucose/Methyl Rapeseedate Ferment, Glycine Soja (Soybean) Sterols This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 8147284820204,
    brand: "ANUA",
    name: "ANUA Heartleaf 70% Intense Calming Cream",
    category: "Moisturizers",
    price: 9.97,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Anua_70_Intense_Calming_Cream.png?v=1771859847",
    description: "Discover this amazing product at The Skin Boutique.",
    ingredients: "Refer to product packaging.",
    reviews: []
  },
  {
    id: 8147248054508,
    brand: "ANUA",
    name: "ANUA Peach 77% Niacin Conditioning Milk (150ml)",
    category: "Moisturizers",
    price: 25.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/processed_cmd0t173y04pon5u662lkxjnv_1752359209469.png?v=1752359213",
    description: "Refreshing milky lotion to hydrate and brighten skin. ANUA Peach 70% Niacin Conditioning Milk is a milky lotion that contains 77% peach extract, ceramide, three types of hyaluronic acid and fermented to smooth and strengthen the skin barrier. With the addition of niacinamide and Vitamin B12, it will also brighten and improve the skin complexion. Features Vegan and cruelty free Non-comedogenic, hypoallergenic Brightens dull skin and supports skin barrier Softens and smooths the skin Improves brightness and skin tone Skin Concerns Dehydrated Skin Dullness Uneven skin tone Skin Types Normal skin types Made In South Korea How to use After cleanser, toner and serum, apply a proper amount onto face and gently pat skin to aid absorption. Apply multiple layers for more intensive moisture. Follow with a moisturizing cream if needed. Ingredients Key Highlights Peach extract 77% Ceramide Niacinamide Ingredient Highlights Alcohol-Free Mineral-Oil Free Paraben-Free Sulfate-Free",
    ingredients: "Full list of ingredients Prunus Persica (Peach) Fruit Extract (77%), Glycerin, Ethylhexyl Stearate, Dipropylene Glycol, Niacinamide (2%), Methyl Trimethicone, 1,2-Hexanediol, Lactobacillus Ferment, Polyglyceryl-3 Distearate, Cetearyl Alcohol, Hydrogenated Poly(C6-12 Olefin), Prunus Persica (Peach) Flower Extract, Sodium Hyaluronate, Glyceryl Stearates, Sodium Stearoyl Glutamate, Carbomer, Galactomyces Ferment Filtrate, Bifida Ferment Lysate, Water, Arginine, Glyceryl Stearate Citrate, Disodium EDTA, Adenosine, Methylpropanediol, Betaine Salicylate, Panthenol, Cyanocobalamin, Ceramide NP, Saccharomyces Ferment Filtrate, Hydrolyzed Hyaluronic Acid, Sodium Acetylated Hyaluronate, Fragrance, Hydroxyacetophenone, Ethylhexylglycerin This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 158, // Fixed dummy IDs
    brand: "ANUA",
    name: "ANUA Heartleaf 77% Clear Pad (70pcs)",
    category: "Toners",
    price: 24.97,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/ANUA_Heartleaf_77_Clear_Pad.png?v=1754404858",
    description: "A one-step toner pad featuring 77% heartleaf and AHA for exfoliation.\nANUA Heartleaf 77% Clear Pad is a convenient, exfoliating toner pad suitable for sensitive acne-prone skin. Combined with the soothing and purifying properties of Heartleaf, this textured toner pads will reveal clea...",
    ingredients: "Refer to product packaging.",
    reviews: []
  },
  {
    id: 7969926906092,
    brand: "ANUA",
    name: "ANUA Heartleaf Quercetinol Pore Deep Cleansing Foam (150ml)",
    category: "Cleansers",
    price: 16.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/anua_q_2.png?v=1752372549",
    description: "A delicate foam cleanser infused with heartleaf extract to deep cleanse combination-oily skin. ANUA Heartleaf Quercetinol Pore Deep Cleansing Foam is formulated for combination-oily skin types and is suitable for sensitive and acne-prone skin. With 3000ppm of finely ground heartleaf powder, it soothes and calms sensitive skin while removing dead skin cells and impurities. Complemented by triple hyaluronic acid complex, i t ensures thorough moisturization and fortified protection for the skin's barrier. Features Vegan and cruelty free Non-comedogenic, hypoallergenic Calms, soothes and protects sensitive skin Removes dead skin cells and purify pores Skin Concerns Acne Rough skin Clogged Pores Skin Types Combination to Oily, including sensitive skin Made In South Korea How to use Wet skin with water. Using a soft, circular motion, apply the cleanser to your skin and gently massage it. Rinse off the cleanser with lukewarm water Key Highlights Quercetinol: Extracted from Heartleaf and known for its soothing properties, Quercetinol quickly calms the skin. Anti-Sebum P: Contains 4 plant-derived extracts to help make pores look smaller and helps to care sebum production 0.5% BHA: A chemical exfoliant, gently exfoliates dead skin cells much more gently than physical exfoliants like scrubs. Ingredient Highlights Mineral-Oil Free Silicone-Free Paraben-Free Sulfate-Free",
    ingredients: "Full list of ingredients Houttuynia Cordata Water (33.32%), Glycerin, Sodium Cocoyl Glycinate, Water, Sodium Lauroyl Glutamate, Coco-Glucoside, Disodium Cocoamphodiacetate, Sodium Chloride, 1,2-Hexanediol, Betaine Salicylate, Potassium Benzoate, Houttuynia Cordata Powder (3000ppm), Polyquaternium-67, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Butylene Glycol, Gardenia Florida Flower Extract, dextrin, Disodium EDTA, Eucalyptus Globulus Leaf Oil, Ethylhexyl Glycerin, Sodium Acetate, Isopropyl Alcohol, Pinus Palustris Leaf Extract, Ulmus Davidiana Root Extract, Oenthera Biennis (Evening Primrose) Flower Exract, Pueraria Lobata Root Extract, Pentylene Glycol, Capryloyl Salicylic Acid, Tocopherol, Hydrolyzed Hyaluronic Acid, Hyaluronic Acid, Hydrolyzed Sodium Hyaluronate, Sodium Hyaluronate, Potassium Hyaluronate, Hydroxylpropyltrimonium Hyaluronate, Sodium Hyaluronate Crosspolymer, Sodium Acetylated Hyaluronate, Quercetin* QUERCETINOL ™ This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 7965277454572,
    brand: "ANUA",
    name: "ANUA Heartleaf 70% Daily Lotion",
    category: "Moisturizers",
    price: 24.97,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/processed_cmd0szv5b04pcn5u6mes84uos_1752358532920.png?v=1752358537",
    description: "A daily lotion that hydrates and soothes sensitive skin. ANUA Heartleaf 70% Daily Lotion is a lotion that can be used year-round with it's moisturizing and soothing . It contains 70% Houttuynia Cordata Extract (heartleaf) and 3 types of hyaluronic acid to soothe and deeply hydrate the skin while also strengthening the skin barrier. With the environment in mind, the packaging is also easily recyclable. Features Vegan and cruelty free Non-comedogenic, hypoallergenic Non-sticky with a refreshing and hydrating finish Deep hydration with 3 types of hyaluronic acid Easily recyclable packaging Skin Concerns Dehydrated Skin Redness &amp; Irritation Acne Skin Types Dry skin types, including acne-prone sensitive skin Made In South Korea How to use Pump once or twice on your fingers and smooth over face and neck. Ingredients Key Highlights 70% H outtuynia cordata extract: soothe dry and sensitive skin, reducing irritation and helping to maintain hydration. 3 Types of Hyaluronic Acid: P rovides powerful hydration deep into the skin. Ingredient Highlights Alcohol-Free Mineral-Oil Free Fragrance-Free Paraben-Free Sulfate-Free",
    ingredients: "Full list of ingredients Water, Glycerin, 1,2-Hexanediol, Butylene Glycol, Houttuynia Cordata Extract, Glyceryl Stearate, Arginine, Carbomer, Ethylhexylglycerin, Sodium Stearoyl Glutamate, Glucose, Ulmus Davidiana Root Extract, Amaranthus Caudatus Seed Extract, Hydrogenated Lecithin, Tocopherol, Hydrolyzed Hyaluronic Acid, Sodium Acetylated Hyaluronate, Ethylhexyl Stearate, Trehalose, Laminaria Japonica Extract, Eclipta Prostrata Leaf Extract, Sodium Hyaluronate Skin, Beta-Glucan, Betaine, Ficus Carica (Fig) Fruit Extract, Glyceryl Glucoside, Glyceryl Stearate Citrate, Polyglyceryl-3 Distearate, Squalane, Fructooligosaccharides, Hydrogenated Poly(C6-14 Olefin), Butyrospermum Parkii (Shea) Butter, Centella Asiatica Extract, Methylpropanediol, Fraxinus Rhynchophylla Extract, Ceramide Np, Cetearyl Glucoside, Ocimum Basilicum Flower/Leaf/Stem Extract, Disodium EDTA, Sodium Hyaluronate, Methyl Trimethicone, Caprylic/Capric Triglyceride, Cetearyl Alcohol, Dipropylene Glycol This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 7963906769132,
    brand: "ANUA",
    name: "ANUA Heartleaf 77% Soothing Toner",
    category: "Toners",
    price: 25.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/anua_2.png?v=1752359036",
    description: "Top selling facial toner in South Korea for clear, glass skin. ANUA Heartleaf 77% Soothing Toner is an award-winning toner known for being highly moisturizing, gentle and soothing, even for sensitive acne-prone skin. It is mildly acidic to maintain pH balance and regulate the skin's oil-moisture levels. Houttuynia cordata (Heartleaf) is clinically proven to i nstantly improve hydration, reduce redness in 2 weeks, and decrease the appearance of acne in 4 weeks. Features pH balanced formula Non-comedogenic, gentle, and non-irritating Reduces redness and improves skin tone Balances and regulates sebum production Skin Concerns Redness &amp; Irritation Acne Dehydrated skin Skin Types All skin types Best for Acne-Prone Skin Made In South Korea How to use Apply with cotton pad or pat with fingers all over the face. Key Highlights 77% Houttuynia Cordata Extract Ingredient Highlights Alcohol-Free Mineral-Oil Free Fragrance-Free Paraben-Free Sulfate-Free Silicone-Free",
    ingredients: "Full list of ingredients Houttuynia Cordata Extract(77%), Purified Water, 1,2-Hexanediol, Glycerin, Betaine, Panthenol, Saccharum Officinarum (Sugarcane) Extract, Portulaca Oleracea Extract, Butylene Glycol, Vitex Agnus-Castus Extract, Chamomilla Recutita (Matricaria) Flower Extract, Arctium Lappa Root Extract, Phellinus Linteus Extract, Vitis Vinifera (Grape) Fruit Extract, Apple Fruit Extract, Centella Asiatica Extract, Isopentyldiol, Methylpropanediol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Tromethamine, Disodium EDTA This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 7965274046700,
    brand: "ANUA",
    name: "ANUA Heartleaf 80% Soothing Ampoule",
    category: "Serums",
    price: 8.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/processed_cmd0sznet04pan5u6zb1swi30_1752358486345.png?v=1752358526",
    description: "A moisturizing and soothing ampoule for sensitive skin ANUA Heartleaf 80% Soothing Ampoule is a nourishing and moisturizing ampoule that's suitable for dry, sensitive skin. It contains 80% Houttuynia Cordata Extract (heartleaf) which will soothe and protect sensitive skin from external irritants. The formula is thick and gel-like but is absorbed quickly without a sticky sensation. Features Vegan and cruelty free Non-comedogenic, hypoallergenic Soothes sensitive skin and moisturizes Fast absorbing and non-sticky Skin Concerns Dehydrated Skin Redness &amp; Irritation Skin Types Combination to Oily skin Suitable for acne-prone and sensitive skin Made In South Korea How to use A pply a moderate amount over the face and pat lightly for better absorption. Key Highlights 80% H outtuynia cordata extract Ingredient Highlights Alcohol-Free Mineral-Oil Free Fragrance-Free Paraben-Free Sulfate-Free Silicone-Free",
    ingredients: "Full list of ingredients Houttuynia Cordata Extract(80%), Butylene Glycol, Glycerin, 1,2-Hexanediol, Betaine, Cassia Obtusifolia Seed Extract, Panthenol, Hydroxyethylcellulose, Sodium Hyaluronate, Arginine, Carbomer, Ethylhexylglycerin This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    reviews: []
  },
  {
    id: 8756130447596,
    brand: "ANUA",
    name: "ANUA PDRN Hyaluronic Acid Capsule 100 Serum (30ml)",
    category: "Serums",
    price: 31.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/ANUA_PDRN_Hyaluronic_Acid_Capsule_100_Serum_30ml.png?v=1772984035",
    
    description: "Three synergistic meet to deeply moisturize and plump the skin. The Anua PDRN Hyaluronic Capsule 100 Serum is a powerhouse blend of hydration and skin repair, featuring the rejuvenating benefits of PDRN (Polydeoxyribonucleotide) and 11 types of hyaluronic acids . This serum is crafted to deliver deep hydration, promote skin regeneration, and restore damaged skin for a healthier, more radiant complexion. Its multi-molecular hyaluronic acid formula enhances elasticity and smoothness, making it an essential addition to your daily skincare routine. Perfect for all skin types, it’s your go-to solution for hydrated, supple, and revitalized skin. Features Deeply hydrating Repairs damaged skin Helps with anti-aging using PDRN and collagen Contains 11 types of hyaluronic acid Skin Concerns Dryness Anti-Aging Dullness Skin Types Suitable for all skin types including sensitive skin Made In SOUTH KOREA 🇰🇷 How to use Daily Care: After applying toner, take a suitable amount of serum and gently massage it into your skin until fully absorbed. Night Care: For an overnight hydration boost, layer the serum 2-3 times in place of a sleeping mask to wake up with deeply hydrated, plump skin. Makeup Care: Mix 1-2 drops of the serum with your foundation or base for a radiant, dewy finish that enhances your makeup look. Ingredients Key Ingredients PDRN (Polydeoxyribonucleotide): Aids in skin regeneration and repair. Hyaluronic Acid: Provides deep hydration and improves skin elasticity. Hydrolyzed Collagen: Strengthens the skin barrier. Niacinamide: Enhances skin tone and texture. Ingredient Highlights Cruelty-Free Paraben-Free Alcohol-Free Silicone-Free Sulfate-Free Fragrance-Free Oil-Free",
    ingredients: "Full list of ingredients Purified Water, Butylene Glycol, Propanediol, Glycerin, Hydrolyzed Hyaluronic Acid, 1,2-Hexanediol, Niacinamide, Glyceryl Oleate, Lauryl Glucoside, Myristyl Glucoside, Polyglyceryl-6 Laurate, Hydrogenated Lecithin, Glutathione, Hydrolyzed Collagen, Sodium Hyaluronate, Coptis Root Extract, Adenosine, Sodium DNA, Hyaluronic Acid, Hydrolyzed Sodium Hyaluronate, Hydroxypropyltrimonium Hyaluronate, Potassium Hyaluronate, Sodium Hyaluronate Crosspolymer, Sodium Acetylated Hyaluronate, Neem Leaf and Flower Extract, Ivy Gourd Fruit Extract, Eggplant Fruit Extract, Holy Basil Leaf Extract, Citric Acid, Turmeric Root Extract, Coral Extract, Sodium Citrate, Pentylene Glycol.",
    
    
    reviews: []
  },
  {
    id: 8585851076844,
    brand: "ANUA",
    name: "ANUA 7 Rice Ceramide Hydrating Barrier Serum (50ml)",
    category: "Serums",
    price: 32.00,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/ANUA_7_Rice_Ceramide_Hydrating_Barrier_Serum_50ml.png?v=1772983389",
    
    description: "A hydrating rice serum that brightens and replenishes the skin's moisture barrier. ANUA 7 Rice Ceramide Hydrating Barrier Serum is a daily hydrating serum formulated with ANUA RICERA (Rice + Ceramide), a complex of ceramides and 7 derived from rice. It also contains 3% Niacinamide and Zinc to help control excess sebum. This nourishing and brightening serum leaves a glowing complexion and is suitable for everyday use. Features Vegan and cruelty-free Hydrating, brightening Controls excess sebum Leaves a glowing complexion Skin Concerns Dullness Dehydrated Skin Skin Types Normal skin types Made In South Korea How to use Apply an appropriate amount to the skin after cleansing and toning. Ingredients Key Ingredients 7 Types Of Rice Extract: Help to nourish and deeply hydrate the skin through moisturizing, while improving the appearance of dullness for a more even and radiant complexion. Hyaluronic Acid: Helps the skin feel hydrated and smooth. It supports a plumper appearance and helps make fine lines less noticeable by moisturizing the skin, leaving the skin feeling refreshed. Ceramide: Helps maintain the skin’s moisture barrier. Ingredient Highlights Alcohol-Free Silicone-Free Paraben-Free Fragrance-Free",
    ingredients: "Full list of ingredients Oryza Sativa (Rice) Bran Water, Dipropylene Glycol, Glycerin, Methylpropanediol, Water, Butylene Glycol, Methyl Gluceth-10, Niacinamide, 1,2-He xanediol, Panthenol, Hydroxyethyl Urea, Pentyle ne Glycol, Sodium Polyacrylate, Oryza Sativa (Rice) Extract, Caprylic/Capric Triglyceride, Carbomer, Hydrogenated Lecithin, Ethylhexylglycerin, Poly quaternium-51, Adenosine, Allantoin, Sodium Phy tate, Xanthan Gum, Ceramide NP, Sodium Hyalu ronate, Alpha-Arbutin, Angelica Keiskei Extract, Corchorus Olitorius Leaf Extract, Dioscorea Jap onica Root Extract, Hibiscus Esculentus Fruit Ex tract, Nelumbo Nucifera Root Extract, Beta-Gluc an, Tocopherol, Defatted Rice Bran Extract, Arbu tin, Zinc Stearate, Defatted Rice Bran, Oryza Sa tiva (Rice) Bran, Hydrolyzed Rice Protein, Oryza Sativa (Rice) Seed Protein, Honey Extract, Hyalu ronic Acid, Hydrolyzed Hyaluronic Acid This ingredient list applies to all variants of this product. Actual ingredients of a specific product option might vary from this list as the",
    
    
    reviews: []
  }
];
