import { Product } from '../types';

export const brandBeautyOfJoseonProducts: Product[] = [
  {
    id: 'boj-dynasty-cream',
    slug: 'beauty-of-joseon-dynasty-cream-50ml',
    brand: 'Beauty of Joseon',
    name: 'Dynasty Cream (50ml)',
    category: 'Skincare',
    price: 490,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Product_Images_100_99f4d3bb-4d7d-4342-a823-2e32c1e60b80.png?v=1769089503',
    description: 'Experience the ultimate in Hanbang (traditional Korean herbal medicine) skincare with this luxurious, firming moisturizer. Engineered with 29% Rice Bran Water and 5% Ginseng Root Water, it skillfully delivers deep nourishment and a lasting glow. Fortified with Honey extract and Ceramide NP, this multi-functional cream smooths fine lines while ensuring your skin remains plump and hydrated throughout the day.',
    ingredients: 'Water, Oryza Sativa (rice) Bran Water, Glycerin, Panax Ginseng Root Water, Hydrogenated polydecene, 1,2-Hexanediol, Niacinamide, Squalane, Butylene glycol, Propanediol, Dicaprylate/Dicaprate, Cetearyl Olivate, Sorbitan Olivate, Ammonium acryloyldimethyltaurate/VP Copolymer, Xanthan Gum, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Tromethamine, Carthamus Tinctorius (Safflower) Seed Oil, Hydrogenated Coconut Oil, Glyceryl Acrylate/Acrylic Acid Copolymer, Ethylhexylglycerin, Adenosine, Caprylic/Capric Triglyceride, Disodium EDTA, Hyaluronic Acid, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate, Honey Extract, Ceramide NP, Hydrogenated Lecithin, Coptis Japonica Root Extract, Raphanus Sativus (Radish) Seed Extract, Lycium Chinense Fruit Extract, Theobroma Cacao (Cocoa) Seed Extract, Phellinus Linteus Extract, Dextrin, Scutellaria Baicalensis Root Extract',
    sku: 'BOJ-DYNASTY-50ML',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-relief-sun-aqua-fresh',
    slug: 'beauty-of-joseon-relief-sun-aqua-fresh-rice-b5-50ml',
    brand: 'Beauty of Joseon',
    name: 'Relief Sun : Aqua-Fresh (Rice + B5) (50ml)',
    category: 'Skincare',
    price: 450,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Relief_Sun_Aqua-Fresh_Rice_B5.png?v=1772989575',
    description: 'A sheer and weightless sun cream that delivers high SPF50+ PA++++ protection without the greasy feel. Engineered with 30% Rice Seed Water and Panthenol (B5), it skillfully provides refreshing hydration while soothing skin stressed by UV exposure. Fortified with Hyaluronic Acid, this watery formula glides on smoothly with no white cast, making it perfect for oily and combination skin types.',
    ingredients: 'Water, Oryza Sativa (Rice) Bran Water, Panthenol, Hyaluronic Acid, Butylene Glycol, Dipropylene Glycol, 1,2-Hexanediol, Niacinamide, Silica, Bisabolol, Potassium Cetyl Phosphate, Hydrolyzed Jojoba Esters, Cetearyl Olivate, Sorbitan Olivate, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Ammonium Acryloyldimethyltaurate/Beheneth-25 Methacrylate Crosspolymer, Xanthan Gum, Adenosine, Fructooligosaccharides, Beta-Glucan, Ethylhexylglycerin',
    sku: 'BOJ-RELIEF-AQUA',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-glow-serum',
    slug: 'beauty-of-joseon-glow-serum-propolis-niacinamide-30ml',
    brand: 'Beauty of Joseon',
    name: 'Glow Serum : Propolis + Niacinamide (30ml)',
    category: 'Skincare',
    price: 350,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/BOJ_Glow_Serum.png?v=1774979172',
    description: 'Reveal your healthiest, most radiant "honey skin" with this antiseptic and anti-inflammatory glow serum. Engineered with 60% Propolis Extract and 2% Niacinamide, it skillfully manages sebum production while ensuring deep hydration. Fortified with BHA (Betaine Salicylate), it calms and heals acne-prone skin, leaving your complexion refined and brightened.',
    ingredients: 'Propolis Extract, Dipropylene Glycol, Glycerin, 1,2-Hexanediol, Niacinamide, Ricinus Communis (Castor) Seed Oil, Sodium Hyaluronate, Melia Azadirachta Flower Extract, Curcuma Longa (Turmeric) Root Extract, Ocimum Sanctum Leaf Extract, Corallina Officinalis Extract, Melia Azadirachta Leaf Extract, Melaleuca Alternifolia (Tea Tree) Extract, Centella Asiatica Extract, Calophyllum Inophyllum Seed Oil, Betaine Salicylate, Sodium Polyacryloyldimethyl Taurate, Tromethamine, Polyglyceryl-10 Laurate, Caprylyl Glycol, Ethylhexylglycerin, Dextrin, Pentylene Glycol, Octanediol, Tocopherol, Xanthan Gum, Carbomer',
    sku: 'BOJ-GLOW-SERUM',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-revive-eye-serum',
    slug: 'beauty-of-joseon-revive-eye-serum-ginseng-retinal-30ml',
    brand: 'Beauty of Joseon',
    name: 'Revive Eye Serum : Ginseng + Retinal (30ml)',
    category: 'Skincare',
    price: 450,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Beauty_of_Joseon_Revive_Eye_Serum_Ginseng___Retinal__30ml_-removebg-preview.png?v=1766165762',
    description: 'Wake up to visibly smoother and firmer under-eyes with this advanced retinal formulation. Engineered with 10% Ginseng Root Extract and 2% Retinal Liposome, it skillfully targets fine lines and loss of elasticity. Fortified with Niacinamide and Peptides, this silky serum delivers deep nourishment while minimizing irritation for a rejuvenated look.',
    ingredients: 'Water, Panax Ginseng Root Extract, Glycerin, Dipropylene Glycol, Caprylic/Caprictriglyceride, 1,2-Hexanediol, Hydrogenated Lecithin, Niacinamide, Retinal, Brassica Campestris (Rapeseed) Sterols, Phytosteryl/Behenyl/Octyldodecyl Lauroyl Glutamate, Silica, Sodium Hyaluronate, Tocopherol, Aluminum/Magnesium Hydroxide Stearate, Potassium Cetyl Phosphate, Ceramide NP, Palmitoyltripeptide-5, Disodium EDTA, Ethylhexylglycerin',
    sku: 'BOJ-EYE-SERUM',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-ginseng-essence-water',
    slug: 'beauty-of-joseon-ginseng-essence-water-150ml',
    brand: 'Beauty of Joseon',
    name: 'Ginseng Essence Water (150ml)',
    category: 'Skincare',
    price: 450,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Beauty_of_Joseon_Ginseng_Essence_Water_150ml.png?v=1772988904',
    description: 'Dry and damaged skin will drink up this refreshing Hanbang essence that revitalizes and smooths texture. Engineered with 80% Ginseng Root Water and 2% Niacinamide, it skillfully provides deep hydration while regulating oil production. Fortified with Adenosine and Hyaluronic Acid, it combats external aggressors for a radiant complexion.',
    ingredients: 'Water, Panax Ginseng Root Water, Butylene Glycol, Glycerin, 1,2-Hexanediol, Niacinamide, Water, Hydroxyacetophenone, Glyceryl Glucoside, Xanthna Gum, Panthenol, Dipotassium Glycyrrhizate, Allantoin, Adenosine, Panax Ginseng Callus Culture Extract, Theobroma Cacao(Cocoa) Extract, Dextrin, Glucose, Panax Ginseng Root Extract, Panax Ginseng Berry Extract, Lactobacillus/Panax Ginseng Root Ferment Filtrate, Sodium Hyaluronate, Ethylhexyglycerin, Disodium EDTA',
    sku: 'BOJ-GINSENG-ESSENCE',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-radiance-cleansing-balm',
    slug: 'beauty-of-joseon-radiance-cleansing-balm-100ml',
    brand: 'Beauty of Joseon',
    name: 'Radiance Cleansing Balm (100ml)',
    category: 'Skincare',
    price: 450,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Product_Images_-_2026-01-22T222527.250.png?v=1769091986',
    description: 'Experience a gentle yet effective double cleanse with this nourishing balm that melts away makeup and impurities. Engineered with Rice Bran Water and Grain Extract, it skillfully clarifies the complexion without stripping the natural moisture barrier. Fortified with Sea Buckthorn Oil, it ensures your skin remains cleaned, smooth, and radiant.',
    ingredients: 'Water, Avena Sativa (Oat) Meal Extract, Coix Lacryma-Jobi Ma-yuen Seed Extract, Oryza Sativa (Rice) Extract, Water, Sorbitan Sesquioleate, Glycerin, Propanediol, Butylene Glycol, 1,2-Hexanediol, Caprylyl Glycol, Ethylhexylglycerin',
    sku: 'BOJ-CLEANSING-BALM',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-red-bean-pore-mask',
    slug: 'beauty-of-joseon-red-bean-refreshing-pore-mask-140ml',
    brand: 'Beauty of Joseon',
    name: 'Red Bean Refreshing Pore Mask (140ml)',
    category: 'Skincare',
    price: 450,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Beauty_of_Joseon_Red_Bean_Refreshing_Pore_Mask_140ml.png?v=1772989575',
    description: 'Deeply cleanse and refresh your pores with this nutrient-dense clay mask inspired by traditional skincare. Engineered with 30% Haenam Red Bean Extract and Kaolin, it skillfully absorbs excess sebum and exfoliates dead skin cells. Fortified with Pear and Strawberry extracts, it ensures a smooth, clarified complexion without a tight after-feel.',
    ingredients: 'Phaseolus Angularis Seed Extract, Glycerin, Kaolin, Caprylic/Capric Triglyceride, 1,2-Hexanediol, Phaseolus Angularis Seed Powder, Glyceryl Stearate, Cetearyl Olivate, Sorbitan Olivate, Cetyl Alcohol, Stearyl Alcohol, Water, Pyrus Communis (Pear) Fruit Extract, Ethylhexylglycerin, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Polyisobutene, Fragaria Chiloensis (Strawberry) Fruit Extract, Pyrus Malus (Apple) Leaf Extract, Caprylyl/Capryl Glucoside, Sorbitan Oleate, Hedera Helix (Ivy) Leaf/Stem Extract, Helianthus Annuus (Sunflower) Seed Oil, Tocopherol',
    sku: 'BOJ-REDBEAN-MASK',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-revive-serum',
    slug: 'beauty-of-joseon-revive-serum-ginseng-snail-mucin-30ml',
    brand: 'Beauty of Joseon',
    name: 'Revive Serum : Ginseng + Snail Mucin (30ml)',
    category: 'Skincare',
    price: 350,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Beauty_of_Joseon_Revive_Serum_Ginseng_Snail_Mucin_30ml.png?v=1772989375',
    description: 'Restore your complexion\'s natural vitality with this luxurious Hanbang serum designed for dull skin. Engineered with 63% Ginseng Root Water and 3% Snail Secretion Filtrate, it skillfully promotes skin regeneration and improves elasticity. Fortified with Adenosine and Licorice Root, it ensures your skin looks revitalized and glowing.',
    ingredients: 'Water, Panax Ginseng Root Water, Butylene Glycol, Snail Secretion Filtrate, Dipropylene Glycol, 1,2-Hexanediol, Glycerin, Niacinamide, Propanediol, Trehalose, Carbomer, Tromethamine, Xanthan Gum, Centella Asiatica Extract, Ganoderma Lucidum (Mushroom) Extract, Panax Ginseng Root Extract, Malt Extract, Sodium Polyacrylate, Adenosine, Glyceryl Acrylate/Acrylic Acid Copolymer, Disodium EDTA, Phellinus Linteus Extract, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Forsythia Suspensa Fruit Extract, Lonicera Japonica (Honeysuckle) Flower Extract, Scutellaria Baicalensis Root Extract, Sodium Acetylated Hyaluronate',
    sku: 'BOJ-REVIVE-SERUM',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-glow-deep-serum',
    slug: 'beauty-of-joseon-glow-deep-serum-rice-alpha-arbutin-30ml',
    brand: 'Beauty of Joseon',
    name: 'Glow Deep Serum : Rice + Alpha-Arbutin (30ml)',
    category: 'Skincare',
    price: 350,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Beauty_of_Joseon_Glow_Deep_Serum_Rice_Arbutin_30ml.png?v=1772988792',
    description: 'Engineered with 68% Rice Bran Water and 2% Alpha-Arbutin, this lightweight serum is designed to illuminate and boost skin health. It skillfully targets pigmentation and uneven skin tone by suppressing melanin production. Fortified with Niacinamide, it ensure your skin achieves a brightened, clear, and glass-like complexion.',
    ingredients: 'Water, Oryza Sativa (Rice) Bran Water, Glycerin, Butylene Glycol, 1,2-Hexanediol, Dipropylene Glycol, Arbutin, Methyl Gluceth-20, Panthenol, Polyglycerin-3, Trehalose, Glyceryl Glucoside, Hydrolyzed Jojoba Esters, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Ethylhexylglycerin, Hydroxyethylcellulose, Xanthan Gum, Arginine, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Disodium EDTA, Coptis Japonica Root Extract, Sorbitan Isostearate, Glucose, Cyclohexane, Coix Lacryma-Jobi Ma-Yuen Seed Extract, Glycine Soja (Soybean) Seed Extract, Hordeum Distichon (Barley) Extract, Oryza Sativa (Rice) Extract, Sesamum Indicum (Sesame) Seed Extract, Triticum Vulgare (Wheat) Seed Extract, Vigna Radiata Seed Extract, Zea Mays (Corn) Kernel Extract',
    sku: 'BOJ-GLOW-DEEP',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-ginseng-cleansing-oil',
    slug: 'beauty-of-joseon-ginseng-cleansing-oil-210ml',
    brand: 'Beauty of Joseon',
    name: 'Ginseng Cleansing Oil (210ml)',
    category: 'Skincare',
    price: 480,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Product_Images_45_54cafcf1-9662-474b-9094-a297505c1a68.png?v=1769049509',
    description: 'Experience a deep yet gentle cleanse with this potent oil that effectively dissolves dirt and makeup residue. Engineered with 50% Soybean Oil and 0.1% Ginseng Seed Oil, it skillfully protects the skin barrier while providing antioxidant benefits. Fortified with essential fatty acids, it ensures your skin remains nourished and smooth.',
    ingredients: 'Glycine Soja (Soybean) Oil, Cetyl Ethylhexanoate, Sorbeth-30 Tetraoleate, Olea Europaea (Olive) Fruit Oil, Sorbitan Sesquioleate, Helianthus Annuus (Sunflower) Seed Oil, Tocopherol, Panax Ginseng Seed Oil, Ethylhexylglycerin, Eclipta Prostrata Extract, Panax Ginseng Root Extract, Melia Azadirachta Leaf Extract, Bixa Orellana Seed Oil, Butylene Glycol, Water, 1,2-Hexanediol',
    sku: 'BOJ-CLEANSING-OIL',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-ground-rice-mask',
    slug: 'beauty-of-joseon-ground-rice-and-honey-glow-mask-150ml',
    brand: 'Beauty of Joseon',
    name: 'Ground Rice and Honey Glow Mask (150ml)',
    category: 'Skincare',
    price: 480,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Product_Images_16_1.png?v=1769089503',
    description: 'Revitalize and brighten your skin with this innovative wash-off mask that combines physical and chemical exfoliation. Engineered with 5% Honey and Upcycled Makgeolli Lees, it skillfully delivers deep hydration while improving skin texture. Fortified with Rice Hull Powder, it ensures a gentle scrub that leaves your skin feeling exceptionally soft and luminous.',
    ingredients: 'Water, Kaolin, Honey, Glycerin, Propanediol, Dipropylene Glycol, Oryza Sativa (Rice) Hull Powder, 1,2-Hexanediol, Arginine, Carbomer, Butylene Glycol, Artemisia Princeps Leaf Extract, Hydroxyacetophenone, Ethylhexylglycerin, Sodium Phytate, Oryza Sativa (Rice) Bran Extract, Nelumbo Nucifera Flower Extract, Morus Alba Bark Extract, Disodium EDTA',
    sku: 'BOJ-GROUND-RICE-MASK',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-rice-milk-toner',
    slug: 'beauty-of-joseon-glow-replenishing-rice-milk-150ml',
    brand: 'Beauty of Joseon',
    name: 'Glow Replenishing Rice Milk (150ml)',
    category: 'Skincare',
    price: 450,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Glow_Replenishing_Rice_Milk_150ml.png?v=1772988904',
    description: 'Transform lackluster skin with this milky, replenishing toner inspired by traditional beauty waters. Engineered with Rice Bran Extract and Rice Germ Extract, it skillfully provides moisture and clarifies the complexion. Fortified with Niacinamide and Panthenol, it ensures your skin achieves a healthy, glass-like radiance with every application.',
    ingredients: 'Water, Oryza Sativa (Rice) Bran Extract, Glycerin, Methylpropanediol, Niacinamide, 1,2-Hexanediol, Dicaprylyl Carbonate, Betaine, Hydrogenated Lecithin, Butylene Glycol, Carbomer, Tromethamine, Ethylhexylglycerin, Adenosine, Panthenol, Ceramide NP, Sodium Hyaluronate',
    sku: 'BOJ-RICE-MILK',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-red-bean-gel',
    slug: 'beauty-of-joseon-red-bean-water-gel-100ml',
    brand: 'Beauty of Joseon',
    name: 'Red Bean Water Gel (100ml)',
    category: 'Skincare',
    price: 490,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Red_Bean_Water_Gel_100ml.png?v=1772989575',
    description: 'Ideally suited for oily and combination skin, this lightweight gel moisturizer balances sebum while locking in hydration. Engineered with 44% Haenam Red Bean Extract and a 3-Peptide Complex, it skillfully minimizes oiliness while improving skin elasticity. Fortified with Red Bean extract, it ensures a matte, refreshed finish without weighing the skin down.',
    ingredients: 'Phaseolus Angularis Seed Extract, Water, Butylene Glycol, Glycerin, 1,2-Hexanediol, Methyl Trimethicone, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Tromethamine, Glyceryl Glucoside, C12-14 Pareth-12, Ethylhexylglycerin, Ammonium Acryloyldimethyltaurate/VP Copolymer, Magnesium Ascorbyl Phosphate, Sodium Hyaluronate, Panthenol, Beta-Glucan, Copper Tripeptide-1, Acetyl Hexapeptide-8, Palmitoyl Pentapeptide-4',
    sku: 'BOJ-REDBEAN-GEL',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-calming-mask',
    slug: 'beauty-of-joseon-centella-asiatica-calming-mask-10-pcs',
    brand: 'Beauty of Joseon',
    name: 'Centella Asiatica Calming Mask (10 Sheets)',
    category: 'Skincare',
    price: 420,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Centella_Asiatica_Calming_Mask.png?v=1767459399',
    description: 'Instantly soothe and hydrate stressed skin with this premium Tencel sheet mask set. Engineered with 15% Centella Asiatica Extract and 3 types of Hyaluronic Acid, it skillfully reduces redness and restores moisture. Fortified with Mugwort and Green Tea extracts, it ensures your skin feels calm, hydrated, and deeply recovered.',
    ingredients: 'Water, Centella Asiatica Extract, Glycerin, Butylene Glycol, 1,2-Hexanediol, Propanediol, Sodium Hyaluronate, Artemisia Princeps Leaf Extract, Camellia Sinensis Leaf Extract, Panthenol, Allantoin, Ethylhexylglycerin, Sodium Acetylated Hyaluronate, Hydrolyzed Hyaluronic Acid',
    sku: 'BOJ-CALMING-MASK-10',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-light-on-serum',
    slug: 'beauty-of-joseon-light-on-serum-centella-vita-c-30ml',
    brand: 'Beauty of Joseon',
    name: 'Light On Serum : Centella + Vita C (30ml)',
    category: 'Skincare',
    price: 420,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Light_On_Serum_Centella_Vita_C.png?v=1771864129',
    description: 'Reveal a brighter, more even complexion without the typical irritation of Vitamin C. Engineered with 68% Centella Asiatica Extract and 10% Vitamin C Derivative (3-O-Ethyl Ascorbic Acid), it skillfully targets hyperpigmentation while soothing the skin. Fortified with Citrus Junos Fruit Extract, it ensures a non-sticky, radiant glow for even the most sensitive skin.',
    ingredients: 'Centella Asiatica Extract, 3-O-Ethyl Ascorbic Acid, Glycerin, Water, Dipropylene Glycol, 1,2-Hexanediol, Niacinamide, Butylene Glycol, Beta-Glucan, Sodium Hyaluronate, Ethylhexylglycerin, Citrus Junos Fruit Extract, Adenosine, Disodium EDTA',
    sku: 'BOJ-LIGHT-ON-SERUM',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-calming-serum',
    slug: 'beauty-of-joseon-calming-serum-green-tea-panthenol-30ml',
    brand: 'Beauty of Joseon',
    name: 'Calming Serum : Green Tea + Panthenol (30ml)',
    category: 'Skincare',
    price: 350,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/BOJ_Calming_Serum.png?v=1774979172',
    description: 'Engineered for sensitive and oil-prone skin, this soothing serum effectively calms inflammation and redness. Skillfully formulated with 50% Green Tea Leaf Water and 5% Panthenol, it provides immediate relief while strengthening the skin barrier. Fortified with Centella Asiatica and Mugwort, it ensures your skin remains balanced, hydrated, and protected.',
    ingredients: 'Camellia Sinensis Leaf Water, Water, Methylpropanediol, Glycerin, Panthenol, Butylene Glycol, 1,2-Hexanediol, Chondrus Crispus Extract, Saccharum Officinarum (Sugarcane) Extract, Artemisia Vulgaris Extract, Melia Azadirachta Leaf Extract, Sodium Hyaluronate, Melia Azadirachta Flower Extract, Theobroma Cacao (Cocoa) Seed Extract, Centella Asiatica Extract, Ethylhexylglycerin, Adenosine, Tocopherol, Xanthan Gum, Carbomer',
    sku: 'BOJ-CALMING-SERUM',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-green-plum-cleanser',
    slug: 'beauty-of-joseon-green-plum-refreshing-cleanser-100ml',
    brand: 'Beauty of Joseon',
    name: 'Green Plum Refreshing Cleanser (100ml)',
    category: 'Skincare',
    price: 420,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Green_Plum_Refreshing_Cleanser_100ml.png?v=1772989575',
    description: 'Start your routine with a gentle, pH-balanced cleanse that respects your skin\'s natural barrier. Engineered with 24% Plum Water and 3% Mung Bean Seed Extract, it skillfully removes impurities without stripping moisture. Fortified with botanical extracts, this revitalizing gel formula ensures your skin feels fresh, soft, and perfectly balanced.',
    ingredients: 'Water, Prunus Mume Fruit Water, Cocamidopropyl Hydroxysultaine, Phaseolus Radiatus Seed Extract, Sodium Cocoyl Isethionate, Glycerin, Sodium Chloride, Tea-Cocoyl Glutamate, 1,2-Hexanediol, Diglycerin, Ethylhexylglycerin, Butylene Glycol, Citric Acid, Disodium EDTA',
    sku: 'BOJ-PLUM-CLEANSER',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-green-plum-toner',
    slug: 'beauty-of-joseon-green-plum-refreshing-toner-aha-bha-150ml',
    brand: 'Beauty of Joseon',
    name: 'Green Plum Refreshing Toner : AHA + BHA (150ml)',
    category: 'Skincare',
    price: 450,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Green_Plum_Refreshing_Toner_150ml.png?v=1772988904',
    description: 'A mild daily resurfacing treatment that reveals a smoother, more radiant complexion. Engineered with 25% Green Plum Water and a gentle mix of 2% Glycolic Acid (AHA) and 0.5% Salicylic Acid (BHA), it skillfully exfoliates dead skin cells. Fortified with Mung Bean Extract, it ensures deep hydration while clarifying pores for a refined skin texture.',
    ingredients: 'Water, Prunus Mume Fruit Water, Glycolic Acid, Dipropylene Glycol, 1,2-Hexanediol, Pentylene Glycol, Phaseolus Radiatus Seed Extract, Glycerin, Salicylic Acid, Ethylhexylglycerin, Sodium PCA, Adenosine, Disodium EDTA',
    sku: 'BOJ-PLUM-TONER',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-apricot-peeling-gel',
    slug: 'beauty-of-joseon-apricot-blossom-peeling-gel-100ml',
    brand: 'Beauty of Joseon',
    name: 'Apricot Blossom Peeling Gel (100ml)',
    category: 'Skincare',
    price: 420,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Apricot_Blossom_Peeling_Gel_100ml.png?v=1772984814',
    description: 'Experience the gentlest way to exfoliate with this gommage-type peeling gel inspired by traditional Korean wisdom. Engineered with 19% Prunus Mume Flower Water and 8% Plant-derived Cellulose, it skillfully rolls away dead skin cells and impurities. Fortified with Apple fruit extract, it ensures your skin remains smooth, moisturized, and refreshed without irritation.',
    ingredients: 'Water, Prunus Mume Flower Water, Cellulose, Glycerin, 1,2-Hexanediol, Butylene Glycol, Pyrus Malus (Apple) Fruit Extract, Ethylhexylglycerin, Carbomer, Tromethamine, Allantoin, Disodium EDTA',
    sku: 'BOJ-APRICOT-PEELING',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  },
  {
    id: 'boj-matte-sun-stick',
    slug: 'beauty-of-joseon-matte-sun-stick-mugwort-camelia-18g',
    brand: 'Beauty of Joseon',
    name: 'Matte Sun Stick : Mugwort + Camelia (18g)',
    category: 'Skincare',
    price: 450,
    image: 'https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Matte_Sun_Stick_Mugwort_Camelia.png?v=1766311976',
    description: 'The ultimate sunstick for convenient reapplication with a completely matte finish. Engineered with Mugwort and Camelia extracts, it skillfully protects your skin while controlling excess oil and sebum. Fortified with Silica and Vitamin E, this non-greasy stick glides smoothly over skin or makeup, ensuring your complexion remains fresh and protected throughout the day.',
    ingredients: 'Methyl Methacrylate Crosspolymer, Synthetic Wax, Dibutyl Adipate, Coco-Caprylate/Caprate, Isopropyl Palmitate, Caprylyl Methicone, Dicaprylyl Carbonate, Silica, Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer, Ethylhexyl Triazone, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Artemisia Capillaris Extract, Camellia Sinensis Leaf Extract, Panthenol, Tocopherol, Glycerin',
    sku: 'BOJ-MATTE-SUN-STICK',
    supplierId: 'abw',
    stockStatus: 'in_stock'
  }
];
