import { Product } from '../products';

export const brandDAlbaProducts: Product[] = [
  {
    id: 9094674677996,
    brand: "d'Alba",
    name: "d'Alba White Truffle Double Moisture Cream (60ml)",
    category: "Moisturizers",
    price: 59.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/d_Alba_White_Truffle_Double_Moisture_Cream.png?v=1770233970",
    
    description: "Customizable cream for all skin types featuring luxurious white truffle extracts. d'Alba White Truffle Vegan Double Serum &amp; Cream is a unique 2-in-1 serum and cream that can be mixed in different ratios according to your skin type and preference. The Aqua Serum is hydrating and soothing thanks to ceramides, centella asiatica extract and panthenol. Meanwhile, the Intense Cream is deeply nourishing and firming and contains 8-blending oils and collagen extract with white flower complex to provide an elastic, youthful appearance. It is non-comedogenic and safe for acne-prone skin. Features Customizable serum and cream formulation Hydrates, soothes, nourishes and firms Non-comedogenic Vegan certified Skin Concerns Anti-Aging Dehydrated Skin Skin Types Suitable for all skin types Made In South Korea How to use After cleansing, dispense an appropriate amount and thoroughly mix the two creams. Dehydrated/Oily Skin - Aqua Serum 2 : Intense Cream 1 Combination Skin - Aqua Serum 2 : Intense Cream 1 Dry Skin: Aqua Serum 1 : Intense Cream 2 Gently apply the mixture along the texture of your skin, allowing it to absorb fully. Alternatively, you can apply the serum and cream separately. Key Ingredients Italian White Truffle Extract Ingredient Highlights Vegan and Cruelty-Free Sulfate-Free Alcohol-Free Paraben-Free",
    ingredients: "Full list of ingredients 【Intense Cream】: Water, Glycerin, DPG, Cetyl Ethylhexanoate, Neopentyl Glycol Diheptanoate, Niacinamide, 1,2-Hexanediol, BG, Tuber Magnatum Extract (000m), Hydrogenated Polydecene, Tocopherol, Cetearyl Olivate, Cetearyl Alcohol, Arachidyl Alcohol, Sorbitan Olivate, Sorbitan Stearate, Ozokerite, Behenyl Alcohol, Carbomer, Arginine, Arachidyl Glucoside, Xylitylglucoside, Anhydroxylitol, Allantoin, Hydrogenated Polyisobutene, Collagen Extract, Xylitol, Octoxyglycerin, Adenosine, Glucose, EDTA-2Na, Dipotassium Glycyrrhizate, Rose Extract, Lotus Flower Extract, Daffodil Flower Extract, Madonna Lily Root Extract, Jasmine Extract, Iris Pallida Extract, Freesia Extract, Sunflower Seed Oil, Avocado Oil, Olive Oil, Evening Primrose Oil, Macadamia Seed Oil, Camellia Seed Oil, Propanediol, Cyperus Root Extract, Mannose, Hippophae Rhamnoides Fruit Oil, Soybean Oil, Bixa Orellana Seed Oil, Fragrance 【Aqua Serum】: Water, Glycerin, Sunflower Seed Oil, DPG, Cetyl Ethylhexanoate, Niacinamide, 1,2-Hexanediol, Polyglyceryl-3 Distearate, Hydroxyethyl Acrylate/Acryloyldimethyl Taurate Copolymer, Tuber Magnatum Extract (00000m), Almond Oil, Tocopherol, Tri(caprylic/capric) Glyceride, BG, Cetearyl Olivate, Ozokerite, Methyl Gluceth-20, Sorbitan Olivate, Soybean Oil, Simethicone, Citric Acid, Glyceryl Stearate, Sorbitan Isostearate, Panthenol, Allantoin, Calendula Flower Extract, Centella Asiatica Extract, Octoxyglycerin, Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Adenosine, Xanthan Gum, EDTA-2Na, Dipotassium Glycyrrhizate, Bixa Orellana Seed Oil, Ceramide NP, Hinoki Leaf Extract, Angelica Extract, Sodium Hyaluronate, Fragrance Ingredients subject to change at manufacturer's discretion. Please check the product packaging for the most updated ingredient list.",
    
    
    reviews: []
  },
  {
    id: 8894328930540,
    brand: "d'Alba",
    name: "d'Alba White Truffle Double Layer Revitalizing Serum (30ml)",
    category: "Serums",
    price: 54.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/DALBA-White-Truffle-Double-Layer-Revitalizing-Serum-30ml-Korean-Serum-For-Firming-And-Wrinkles-For-Dullness-and-Anti-Aging-PURESEOUL-UK-KBeauty-Shop.png?v=1747778930",
    
    description: "A double layered serum for firm, healthy and glowy skin. d'Alba White Truffle Double Layer Revitalizing Serum is a 2-in-1 double solution with 30% glowing oil layer and a 70% elastic serum layer that promotes healthy, smooth skin. It uses premium white truffles from Italy and natural essential oils to provide long-lasting moisture and glow. The plant-based organic substances such as sunflower seed oil, macadamia nut oil, avocado oil, etc. provide deep hydration and absorb deep into the pores. The patented substances okra extract and hydrolyzed hyaluronic acid keep skin tissues moist and hydrated. Features Vegan 30% glowing oil layer and a 70% elastic serum layer Long-lasting moisture and glow Deeply hydrates and firms skin with antioxidants Skin Concerns Dullness Dehydrated Skin Anti-aging Skin Types Suitable for all skin types Made In South Korea How to use After cleansing, shake the bottle up and down 3 to 5 times to ensure the contents are well mixed. Pump 2 to 3 times into your palm and gently apply over your entire face, allowing it to absorb. Key Ingredients Italian White Truffle Extract Vitamin E Ingredient Highlights Vegan and Cruelty-Free Sulfate-Free Silicone-Free Paraben-Free Alcohol-Free",
    ingredients: "Full list of ingredients Water, Sunflower Seed Oil, BG, DPG, 1,2-Hexanediol, Macadamia Seed Oil, Tuber Magnatum Extract, Tri(caprylic/capric) Glyceride, Camellia Seed Oil, Evening Primrose Oil, Olive Fruit Oil, Avocado Oil, Meadowfoam Oil, Tocopherol, Fragrance, Arginine, Carbomer, Betaine, Panthenol, Tocopheryl Acetate, Centella Asiatica Extract, Birch Sap, Rosa Centifolia Flower Water, Soybean Oil, Ethylhexylglycerin, Glycerin, Dipotassium Glycyrrhizate, EDTA-2Na, Hippophae Rhamnoides Fruit Oil, Hydroxyethyl Urea, Aloe Vera Leaf Extract, Adenosine, Ocimum Basilicum (Basil) Flower/Leaf/Stem Extract, Avena Sativa (Oat) Kernel Extract, Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Salvia Hispanica Seed Extract, Bifida Ferment Lysate, Okra Fruit Extract, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate, Chamomile Flower Extract, Hibiscus Flower Extract, Lavender Flower Extract, Melissa Leaf Extract, Peppermint Leaf Extract, Apple Mint Leaf Extract, Monarda Didyma Leaf Extract, Rosa Centifolia Flower Extract, Rosemary Leaf Extract, Sage Leaf Extract, Sodium Palmitoyl Proline, Bixa Orellana Seed Oil, Potassium Sorbate, Daisy Flower Extract, Chlorphenesin, Freesia Extract, Houttuynia Cordata Extract, Edelweiss Extract, Madonna Lily Flower Extract, Mulberry Bark Extract, Lotus Flower Extract, Ginseng Root Extract, Saussurea Involucrata Extract, Nymphaea Alba Flower Extract. Ingredients subject to change at manufacturer's discretion. Please check the product packaging for the most updated ingredient list.",
    
    
    reviews: []
  },
  {
    id: 9050762838252,
    brand: "d'Alba",
    name: "d'Alba White Truffle Prime Intensive Serum (100ml)",
    category: "Serums",
    price: 32.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/kshopbeauty.vn-dAlba-White-Truffle-Prime-Intensive-Solution-Serum.png?v=1761840441",
    
    description: "A double layered serum mist for hydrated and glowy skin. d'Alba White Truffle Prime Intensive Serum is a vegan-certified anti-aging serum mist engineered to restore elasticity and luminosity. This innovative serum merges dual-capsule technology—encapsulated oils and peptides—with a potent serum concentrate to target fine lines and loss of firmness. Harnessing Trufferol and Vitamin E, it delivers six times the antioxidant strength of propolis. The precision mist application distributes evenly across skin, delivering a dewy, hydrated glow without stickiness or buildup. Complemented by an elegant aromatic citrus floral fragrance created in partnership with Italian perfumer Giovanni Festa, this serum elevates your daily skincare ritual. Features Vegan Micro oil and serum capsules in a mist Long-lasting moisture and glow Aromatic Citrus Floral Fragrance Skin Concerns Dullness Dehydrated Skin Anti-aging Skin Types Suitable for all skin types Made In South Korea How to use After cleansing, shake the bottle up and down 3 to 5 times to ensure the contents are well mixed. Pump 2 to 3 times into your palm and gently apply over your entire face, allowing it to absorb. Key Ingredients Italian White Truffle Extract Vitamin E Collagen Ingredient Highlights Vegan and Cruelty-Free Sulfate-Free Silicone-Free Paraben-Free Alcohol-Free",
    ingredients: "Full list of ingredients Collagen Extract, Helianthus Annuus (Sunflower) Seed Oil, Dipropylene Glycol, 1,2-Hexanediol, Glyceryl-26, Niacinamide, Tuber Magnatum Extract (White Truffle Extract), Polypropyl Silsesquioxane, Tocopherol, Caprylic/Capric Triglyceride, Butylene Glycol, Macadamia Integrifolia Seed Oil, Aqua (Water), Hydroxyethyl Urea, Betaine, Camellia Japonica Seed Oil, Persea Gratissima (Avocado) Oil, Saccharide Isomerate, Glyceryl Glucoside, Ethylhexylglycerin, Simmondsia Chinensis (Jojoba) Seed Oil, Olea Europaea (Olive) Fruit Oil, Pentaerythrityl Tetra-Di-T-Butylhydroxyhydrocinnamate, Disodium EDTA, Carthamus Tinctorius (Safflower) Seed Oil, Dipotassium Glycyrrhizate, Adenosine, Phaseolus Radiatus (Mung Bean) Seed Extract, Oenothera Biennis (Evening Primrose) Oil, Glycerin, Hydrogenated Polydecene, Mannose, Glucose, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Arginine, Bixa Orellana (Annatto) Seed Oil, Hippophae Rhamnoides (Sea Buckthorn) Fruit Oil, Sodium Citrate, Citric Acid, Agar, Guar Gum, Xanthan Gum, Palmitoyl Pentapeptide-4, Hydrolyzed Barley Protein, Hydrolyzed Corn Protein, Copper Tripeptide-1, Acetyl Hexapeptide-8, Glycoprotein, Hydrolyzed Lupine Protein, Hydrolyzed Oat Protein, Hydrolyzed Pea Protein, Hydrolyzed Potato Protein, Hydrolyzed Rice Protein, Hydrolyzed Soy Protein, Hydrolyzed Vegetable Protein, Hydrolyzed Wheat Protein, Parfum (Fragrance), Linalool, Hexyl Cinnamal, Limonene, Citronellol. Ingredients subject to change at manufacturer's discretion. Please check the product packaging for the most updated ingredient list.",
    
    
    reviews: []
  },
  {
    id: 9049820365036,
    brand: "d'Alba",
    name: "d'Alba White Truffle Royal Intensive Serum (100ml)",
    category: "Serums",
    price: 32.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/4rzkd3tzksa84h6hctphwdhddv3j.webp?v=1761583274",
    
    description: "A biphase serum mist that offers a boost of instant hydration. d'Alba White Truffle Royal Intensive Serum transforms your skin with a luxurious mist that combines brightening power with anti-aging benefits. This innovative bi-phase formula harnesses Italian white truffle, glutathione, peptides, and plant-based collagen to deliver visible radiance and firmness in seconds. The fine mist absorbs effortlessly, creating 15 layers of hydration that cling to every skin contour without stickiness or heaviness. Whether your skin needs luminosity, elasticity, or deep moisture, this multitasking serum works for all skin types—especially those seeking a glassy, transparent glow. Spray it anytime, anywhere for skin that looks refreshed, youthful, and undeniably radiant. Features Vegan Biphase formula that brightens and anti-ages Long-lasting moisture and glow Fine mist that can be used anytime Skin Concerns Dullness Dehydrated Skin Anti-aging Skin Types Dry to combo skin Made In South Korea How to use After cleansing, shake the bottle up and down 3 to 5 times to ensure the contents are well mixed. Close eyes and spray 4-5 times from a distance of 20-25cm. Key Ingredients Italian White Truffle Glutathione Peptides Collagen Ingredient Highlights Vegan and Cruelty-Free Sulfate-Free Silicone-Free Paraben-Free Alcohol-Free",
    ingredients: "Full list of ingredients Collagen Extract, Helianthus Annuus (Sunflower) Seed Oil, Dipropylene Glycol, 1,2-Hexanediol, Niacinamide, Glyceryl-26, Tuber Magnatum Extract (White Truffle Extract), Polypropyl Silsesquioxane, Tocopherol, Butylene Glycol, Caprylic/Capric Triglyceride, Macadamia Integrifolia Seed Oil, Aqua (Water), Hydroxyethyl Urea, Betaine, Persea Gratissima (Avocado) Oil, Camellia Japonica Seed Oil, Saccharide Isomerate, Glycine Soja (Soybean) Oil, Ethylhexylglycerin, Glycerin, Lauryl Glucoside, Simmondsia Chinensis (Jojoba) Seed Oil, Pentaerythrityl Tetra-Di-T-Butylhydroxyhydrocinnamate, Carthamus Tinctorius (Safflower) Seed Oil, Olea Europaea (Olive) Fruit Oil, Argania Spinosa Kernel Oil, Rosa Canina (Rosehip) Fruit Oil, Dipotassium Glycyrrhizate, Disodium EDTA, Adenosine, Oenothera Biennis (Evening Primrose) Oil, Hydrogenated Polydecene, Mannose, Glucose, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Arginine, Bixa Orellana (Annatto) Seed Oil, Hippophae Rhamnoides (Sea Buckthorn) Fruit Oil, Citric Acid, Sodium Citrate, Agar, Guar Gum, Hydrolyzed Soy Protein, Hydrolyzed Pea Protein, Hydrolyzed Rice Protein, Hydrolyzed Lupine Protein, Hydrolyzed Potato Protein, Hydrolyzed Corn Protein, Hydrolyzed Oat Protein, Hydrolyzed Sweet Almond Protein, Hydrolyzed Barley Protein, Hydrolyzed Wheat Protein, Hydrolyzed Jojoba Protein, Hydrolyzed Silk Protein, Glycoprotein, Rosa Centifolia Flower Oil, Glutathione, Xanthan Gum, Palmitoyl Pentapeptide-4, Copper Tripeptide-1, Acetyl Hexapeptide-8, Parfum (Fragrance), Linalool, Hexyl Cinnamal, Limonene, Citronellol. Ingredients subject to change at manufacturer's discretion. Please check the product packaging for the most updated ingredient list.",
    
    
    reviews: []
  }
];
