import { Product } from '../products';

export const brandMeditherapyProducts: Product[] = [
  {
    id: 9009780916460,
    brand: "MEDITHERAPY",
    name: "MEDITHERAPY Tranexamic Acid Skin Booster Cream + Booster Cap (100ml)",
    category: "Moisturizers",
    price: 89.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Meditherapy_Tranexamic_Acid_Skin_Booster.png?v=1759262632",
    
    description: "Innovative all-in-one K-beauty cream and microcurrent booster device MEDITHERAPY Tranexamic Acid Skin Booster Cream with microcurrent booster cap is K-beauty innovation at its finest. This advanced formula combines 5% Niacinamide and 3% Tranexamic Acid to visibly brighten and even out your skin tone while improving clarity, elasticity, and radiance. The silky, fast-absorbing cream hydrates deeply without any sticky residue, making it comfortable for all skin types, including sensitive and blemish-prone skin. Clinically tested for low irritation, this K-beauty breakthrough offers professional-grade results at home, targeting dullness, fine lines, and dark spots effortlessly. Features Comes with re-usable microcurrent booster cap 770% increased absorption with microcurrent cap Silky, fast-absorbing, non-sticky cream Brightens and refines uneven skin tone Treats dullness, fine lines, pigmentation, and pores Skin Concerns Enlarged Pores Anti-aging Dullness Uneven Skin Pigmentation Skin Types Suitable for all skin types Made In KOREA 🇰🇷 How to use Apply the Skin Booster Cream evenly to clean, dry skin. Use the Booster Cap device on desired areas for 3 minutes, up to twice a day. Use Level 1 for sensitive zones such as eyes or lips. For manual use, gently massage the cream in upward strokes until absorbed. Avoid use on damaged or hypersensitive skin. Key Ingredients 5% Niacinamide: Brightens, smooths, and strengthens skin barrier 3% Tranexamic Acid: Reduces dark spots and discoloration 80,000ppm tone-refining complex: Targets dull tone and uneven texture Ingredient Highlights Sulfate-Free Paraben-Free Mineral-Oil Free Acohol-Free Fragrance-Free Silicone-Free",
    ingredients: "Full list of ingredients Aqua (Water), Niacinamide (10%), Butylene Glycol, Glycerin, Arbutin (2%), 1,2-Hexanediol, Caprylic/Capric Triglyceride, Hydroxyacetophenone, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Arginine, Ethylhexylglycerin, Adenosine, Xanthan Gum, Disodium EDTA, Ceratonia Siliqua (Carob) Gum, Rosa Canina Fruit Oil, Tocopheryl Acetate, Sucrose, Alpha-Arbutin (1ppm) Ingredients subject to change at manufacturer's discretion. For the most complete and up-to-date list of ingredients, please refer to product packaging.",
    
    
    reviews: []
  },
  {
    id: 9009779409132,
    brand: "MEDITHERAPY",
    name: "MEDITHERAPY Tension Up Mask",
    category: "Masks",
    price: 32.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Meditherapy_Tension_Up_Mask.png?v=1759254012",
    
    description: "Quick and effective at-home face lift for a snatched V-line. MEDITHERAPY Tension Up Mask gives you an immediate lifted and sculpted V-line at home. This innovative mask sharpens your facial contours from the first application while diminishing puffiness and reducing double-chin volume. It firms sagging skin and smooths nasolabial folds, leaving your skin deeply hydrated and silky-soft without any stickiness. Featuring a triple-zone design that targets the cheekbones, jawline, and forehead, plus a high-elasticity hydrogel for a snug, comfortable fit, this mask delivers proven results. Powered by Matrixyl 3000, Centella, caffeine, and sea buckthorn, it enhances skin firmness and radiance for a youthful glow. Features Highly concentrated hydrogel to deliver Hydrating and refreshing finish Lifts and sculpts skin for a snatched V-lift Improvements seen after 4 weeks of use Skin Concerns Anti-aging Skin Types Suitable for all skin types Made In KOREA 🇰🇷 How to use Ensure skincare products are fully absorbed first Remove white film and apply pieces in following order: cheekbones, forehead, jawline Attach around the mouth area first then pull upward toward the eyes to lift the cheeks Attach forehead piece just above the brows, holding the two pointed ends and pull them upward to adjust Hold the ear hooks with both hands, position the center on the middle of the chin and gently press it behind the ears to secure Ingredients Key Ingredients Hippophae Phamnoides Fruit: nourish and improve skin elasticity Matrixyl 3000: stimulates collagen for a firm and tightening effect Centella Asiatica: supports collagen production for firmer, smoother skin Caffeine: reduces puffiness and energizes the skin for a fresh, glowing look Ingredient Highlights Sulfate-Free Paraben-Free Mineral-Oil Free",
    ingredients: "Full list of ingredients Water, Glycerin, Propanediol, Niacinamide, 1,2-Hexanediol, Caffeine, Diethoxyethyl Succinate, Butylene Glycol, Ammonium Acryloyldimethyltaurate/VP Copolymer, C12-14 Alketh-12, Carbomer, Tromethamine, Adenosine, Sodium Lactate, Polysorbate 20, Vanillyl Butyl Ether, Calcium Alginate, Gellan Gum, Agar, Caprylyl Glycol, Calcium Aluminum Borosilicate, Palmitoyl Oligopeptide(3ppm), Palmitoyl Tetrapeptide- 7(1.5ppm), Glucose, Acetyl Hexapeptide-8(396ppb), Bromelain, Caprylic/Capric Triglyceride, Hydrogenated Lecithin, Polyglyceryl-10 Diisostearate, Polyglyceryl-10 Stearate, Panthenol, Menadione, Sodium Ascorbyl Phosphate, Pyridoxine, Biotin, Tocopherol, Cyanocobalamin, Thiamine HCl, sh-Polypeptide-1 (0.001ppb), sh-Oligopeptide-2(0.001ppb), sh-Oligopeptide-1(0.001ppb), Beta-Carotene, Riboflavin, Titanium Dioxide Ingredients subject to change at manufacturer's discretion. For the most complete and up-to-date list of ingredients, please refer to product packaging.",
    
    
    reviews: []
  },
  {
    id: 9009777213676,
    brand: "MEDITHERAPY",
    name: "MEDITHERAPY Wrinkle-Fit Mask (7 PCs)",
    category: "Masks",
    price: 32.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Meditherapy_Wrinkle-Fit_Mask.png?v=1759413395",
    
    description: "Top-selling anti-wrinkle mask with at-home needle roller for maximum effects MEDITHERAPY Wrinkle-Fit Mask soothes and deeply hydrates with a specially designed mesh sheet mask that works beneath the skin’s surface while the boosting roller gently firms and tightens for a revitalized look. Its high moisture-binding ability locks in hydration, enhancing skin elasticity and diminishing the look of wrinkles, leaving your skin nourished and supple. Combine the Wrinkle-Fit Mask with the Boosting Roller to maximize absorption and refresh your complexion. Inspired by Korean beauty, this easy-to-use home care set delivers firming and moisturizing effects that help maintain healthy, glowing skin. Features Restores skin elasticity with collagen and hyaluronic acid Counters skin sagging Reaches into fine lines and wrinkles Thread sheet coated with ampoule Best results with Wrinkle-Fit Needle Roller Skin Concerns Anti-aging Dullness Skin Types Suitable for all skin types Made In KOREA 🇰🇷 How to use After cleansing, apply toner to prepare your skin Place Wrinkle-Fit Sheet Mask on your face Gently roll the facial over your face for 10-15 minutes remove mask and lightly pat the remaining essence into your skin Key Ingredients Hyaluronic Acid: high moisture binding capacity helps with skin's elasticity and moisture Collagen: grants skin elasticity and helps maintain shine Volufiline: provides deep nourishment to the skin 9 types of peptides: aids in firming skin Ingredient Highlights Silicone-Free Sulfate-Free Mineral Oil-Free Paraben-Free",
    ingredients: "Full list of ingredients Purified Water, Glycerin, Denatured Alcohol, Dipropylene Glycol, Propanediol, Butylene Glycol, 1,2-Hexanediol, Arginine, Hydroxyacetophenone, Acrylate/C10-30 Alkyl Acrylate Crosspolymer, Carbomer, Allantoin, Glycereth-25 PCA Isostearate, Adenosine, Glycereth-26, Ethylhexylglycerin, Disodium EDTA, Biosaccharide Gum-1, Fragrance, Hydrogenated Polyisobutene, Hyaluronic Acid, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate, Portulaca Oleracea Extract, Hydroxyethyl Cellose, Mentha Aquatica Extract, Ammonium Polyacryloyldimethyl Taurate, Centella Asiatica Extract, Camellia Japonica Flower Extract, Houttuynia Cordata Extract, Menthol, Melaleuca Alternifolia (Tea Tree) Leaf Extract, Petroselinum Sativum (Parsley) Extract, Caprylic/Capric Triglyceride, Hydrolyzed Collagen, Polyglyceryl-10 Oleate, Water-Soluble Collagen, Hydrogenated Lecithin, Anemarrhena Asphodeloides Root Extract, Hydroxydecyl Ubiquinone, Tocopherol, Tripeptide-3, Acetyl Hexapeptide-8, Acetyl Octapeptide-3, Atelo Collagen, Copper Tripeptide-1, Palmitoyl Pentapeptide-4, Palmitoyl Tetrapeptide-7, Palmitoyl Tripeptide-1, Tripeptide-1, Tripeptide-2 Ingredients subject to change at manufacturer's discretion. For the most complete and up-to-date list of ingredients, please refer to product packaging.",
    
    
    reviews: []
  },
  {
    id: 9009778917612,
    brand: "MEDITHERAPY",
    name: "MEDITHERAPY Retinal Skin Booster Serum (150ml)",
    category: "Serums",
    price: 32.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Meditherapy_Retinal_Skin_Booster_Serum.png?v=1759251172",
    
    description: "All-in-one daily glow reset MEDITHERAPY Retinal Skin Booster Serum offers a powerful yet gentle formula ideal for sensitive and acne-prone skin. Enriched with retinal, it enhances skin texture and minimizes pores, while the calming Cica Biome Complex—featuring four plant extracts and Centella probiotics—soothes and protects. Its lightweight, fast-absorbing texture leaves no residue and works on both face and body to smooth dry, rough patches. With retinaldehyde’s superior absorption, it penetrates deeply to reduce redness and irritation. Regular use boosts radiance, refines texture, and improves skin firmness, visibly reducing wrinkles for a youthful glow within four weeks. Features Retinol suitable for beginners and sensitive skin Generous size for face and body Reduces wrinkles and boosts collagen Smooths rough texture and troubled skin Lightweight and watery texture Skin Concerns Anti-aging Rough skin Enlarged pores Dullness Uneven skin Skin Types Suitable for all skin types, including sensitive skin Made In KOREA 🇰🇷 How to use After completing your skincare routine, apply a moderate amount of the cream evenly across your face. Gently pat the cream into your skin to enhance absorption. Key Ingredients Retinal Liposome Cica Biome Centella-derived Probiotics Ingredient Highlights Vegan Sulfate-Free Paraben-Free Mineral-Oil Free Alcohol-Free Fragrance-Free",
    ingredients: "Full list of ingredients Water, Methylpropanediol, Glycerin, Caprylic/Capric Triglyceride, 1,2-Hexanediol, Propanediol, Polyglycerin-3, Niacinamide, Phenyl Trimethicone, Ammonium Acryloyldimethyltaurate/VP Copolymer, Butylene Glycol, Sodium Acrylic Acid/MA Copolymer, Pentaerythrityl Tetra-di-t-butyl Hydroxyhydrocinnamate, Xanthan Gum, Macadamia Ternifolia Seed Oil, Hydrogenated Lecithin, Ethylhexylglycerin, Adenosine, Carbomer, Disodium EDTA, Tromethamine, Polyglyceryl-10 Laurate, Sodium Hyaluronate, Cholesterol, Tocopherol, Brassica Campestris (Rapeseed) Sterols, Retinal (100ppm), Ascorbyl Tetraisopalmitate, Potentilla Anserina Extract, Caprylyl Glycol, Aluminum/Magnesium Hydroxide Stearate, Polyquaternium-51, Cynara Scolymus (Artichoke) Leaf Extract, Avena Sativa (Oat) Kernel Extract, Beta-Glucan, Potassium Cetyl Phosphate, Camellia Sinensis Leaf Water, Piper Methysticum Leaf/Root/Stem Extract, Sodium Ascorbyl Phosphate, Centella Asiatica Extract, Ficus Carica (Fig) Fruit Extract, Ceramide NP, Centella Asiatica Leaf Extract, Saccharomyces Ferment, Centella Asiatica Root Extract, Canola Oil, Myristyl Alcohol, PCA, Acetyl Hexapeptide-1, Asiaticoside, Madecassoside, Daucus Carota Sativa (Carrot) Seed Oil, Bifida Ferment Lysate, Lactobionic Acid, Daucus Carota Sativa (Carrot) Root Extract, Tocopheryl Acetate, Beta-carotene, Helianthus Annuus (Sunflower) Seed Oil, Panthenol, Polygonum Cuspidatum Root Extract, Sucrose Distearate, Hydroxypropyl Cyclodextrin, Madecassic Acid, Asiatic Acid Ingredients subject to change at manufacturer's discretion. For the most complete and up-to-date list of ingredients, please refer to product packaging.",
    
    
    reviews: []
  },
  {
    id: 9009777836268,
    brand: "MEDITHERAPY",
    name: "MEDITHERAPY Wrinkle-Fit Tangle Eye Patch (4 Pairs)",
    category: "Eye Care",
    price: 21.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Meditherapy_Wrinkle-Fit_Tangle_Eye_Patch.png?v=1759412240",
    
    description: "Plump, smooth and brighten under-eyes and cheeks with these mega-sized patches Meditherapy Wrinkle-Fit Tangle Eye Patch deeply hydrates and firms with a generous formula of French collagen. It diminishes fine lines, alleviates puffiness, and brightens dark circles around the eyes while antioxidants shield your skin from environmental harm, leaving it soft and radiant. Perfect for sensitive skin, it also calms irritation for a youthful appearance. Infused with 70% high-quality French collagen, these hydrogel patches restore firmness and impart a luminous glow, instantly revitalizing tired eyes. Their large 3.5-inch size covers a broader area, including cheeks, ensuring comprehensive care. Free from parabens and synthetic additives, these cruelty-free patches deliver fresh, pure nourishment every time. Features Features premium collagen from France Rejuvenates and freshens tired, aging eye area Reduces fine lines, puffiness and dark circles within 2 weeks Large 3.5 inch patch to treat beyond eye area Skin Concerns Anti-aging Dark circles Skin Types Suitable for all skin types Made In KOREA 🇰🇷 How to use Remove any grease to ensure proper adhesion Peel off the protective film and attach the plain side onto the under-eye. Leave the patches on while sleeping (Leave it at least for 20 minutes). Afterwards, carefully remove the patches and gently pat any remaining essence. Key Ingredients French Hydrolyzed Collagen Hyaluronic Acid Hydrolyzed Elastin Ingredient Highlights Cruelty-Free Sulfate-Free Paraben-Free Mineral-Oil Free Alcohol-Free Silicone-Free",
    ingredients: "Full list of ingredients Hydrolyzed Collagen(701,376.2ppm), Glycerin, Water, Acrylates Copolymer, 1,2-Hexanediol, Niacinamide, Carrageenan, Ceratonia Siliqua (Carob) Gum, Potassium Chloride, Xanthan Gum, Allantoin, Gellan Gum, Trehalose, Sucrose, Cellulose Gum, Betaine, Panthenol, Hydroxyacetophenone, Sodium Polyacrylate, Caprylyl Glycol, Butylene Glycol, Propanediol, Polyglyceryl-10 Laurate, Artemisia Princeps Leaf Extract, Ethylhexylglycerin, Adenosine, Fragrance, Snail Secretion Filtrate, Citrus Junos Fruit Extract, Camellia Sinensis Leaf Extract, Lecithin, Arginine, Hydrolyzed Elastin, Sodium Hyaluronate, Ethyl Hexanediol, Ceramide NP, Tocopheryl Acetate, Phellodendron Amurense Bark Extract, Paeonia Lactiflora Root Extract, Agrimonia Pilosa Extract, Glycyrrhiza Uralensis (Licorice) Root Extract, Houttuynia Cordata Extract, sh-Oligopeptide-1, sh-Oligopeptide-2, sh-Polypeptide-1, sh-Polypeptide-22 Ingredients subject to change at manufacturer's discretion. For the most complete and up-to-date list of ingredients, please refer to product packaging.",
    
    
    reviews: []
  }
];
