import { Product } from '../products';

export const brandMedipeelProducts: Product[] = [
  {
    id: 9083753234668,
    brand: "MEDIPEEL",
    name: "MEDIPEEL Red Lacto Collagen Wrapping Mask (70ml)",
    category: "Masks",
    price: 26.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/MEDIPEEL_Red_Lacto_Collagen_Wrapping_Mask_70ml.png?v=1771867524",
    
    description: "Silicone-free brightening cream to fade dark spots and even skin tone. AXIS-Y TXA 2.5% Intensive Brightening Cream is a gentle yet effective formula designed to target dullness and uneven skin tone while delivering deep hydration. Infused with 2.5% Tranexamic Acid, 2.5% Niacinamide, and Glutathione, this nourishing, silicone-free cream works to visibly fade dark spots, refine tone, and restore luminosity. The soft, balm-like texture melts seamlessly into the skin, providing a soothing and silky finish that supports smoother, brighter, and more balanced skin. Features Brightens and evens skin tone Deeply hydrates and nourishes Soothes and comforts Silky, balm-like texture Skin Concerns Dark Spots Hyperpigmentation Dehydrated skin Skin Types Suitable for all skin types, including sensitive skin Made In South Korea How to use Apply a pea-sized amount and gently press into the skin to help it absorb. Key Ingredients Tranexamic Acid 2.5%: Helps fade dark spots and discoloration for a clearer, more even complexion Niacinamide 2.5%: Refines uneven tone and strengthens the skin barrier for a smooth, luminous finish Glutathione: A powerful antioxidant that supports brighter, healthier-looking skin Ceramide: Locks in moisture and reinforces the skin barrier to prevent dryness Hyaluronic Acid: Deeply hydrates and plumps the skin, helping to restore a soft, supple feel Cica &amp; Heartleaf: Gently calm irritation and support balanced, healthy skin — perfect for sensitive skin Ingredient Highlights Sulfate-Free Mineral Oil Free Cruelty-Free Fragrance-Free Paraben-Free Alcohol-Free Silicone-FRee",
    ingredients: "Full list of ingredients Water, Glycerin, Dicaprylyl Ether, Hydrogenated Polydecene, Stearyl Alcohol, Butyrospermum Parkii (Shea) Butter, Niacinamide, Tranexamic Acid(2.5%), Octyldodecanol, Pentaerythrityl Tetraethylhexanoate, Behenyl Alcohol, Panthenol, 1,2-Hexanediol, Arachidyl Alcohol, Dipentaerythrityl Hexahydroxystearate/Hexastearate/Hexarosinate, Cetearyl Olivate, Sorbitan Olivate, Citric Acid, Arachidyl Glucoside, Garcinia Cambogia Fruit Extract, Hydroxyacetophenone, Palmitic Acid, Stearic Acid, Ammonium Acryloyldimethyltaurate/VP Copolymer, Ceramide NP, Carbomer, Ethylhexylglycerin, Disodium EDTA, Glutathione, Butylene Glycol, Tocopherol, Centella Asiatica Extract, Houttuynia Cordata Extract, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Sodium Acetylated Hyaluronate",
    
    
    reviews: []
  },
  {
    id: 9083753103596,
    brand: "MEDIPEEL",
    name: "MEDIPEEL Phyto Exosome PDRN Lifting Shot Eye Cream (40ml)",
    category: "Eye Care",
    price: 25.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Phyto_PDRN_Lifting_Shot.png?v=1765402813",
    
    description: "A cream with a lifting effect for mature skin, aimed at combating age-related changes in the areas around the eyes MEDIPEEL Phyto Exosome PDRN Lifting Shot Eye Cream reduces signs of aging and firms up the delicate skin around the eyes. The synergy of rejuvenating active helps smooth out the wrinkle network, eliminates swelling and dark circles, strengthens and tightens the skin, preventing the appearance of wrinkles. It also lifts, moisturizes, nourishes, stimulates regeneration, and prevents flaking and dryness. The active ingredients used will penetrate deep into the skin thanks to the inclusion of phyto exosomes and apple stem cells. Features Brightens and evens skin tone Non-irritating and prevents the formation of dark circles and crow's feet Soothes and comforts Silky, balm-like texture Skin Concerns Dark Spots Hyperpigmentation Dehydrated skin Skin Types Suitable for all skin types, including sensitive skin Made In South Korea How to use Apply the cream to the area around the eyes, avoiding contact with the mucous membrane, and distribute with light patting movements. Ingredients Key Ingredients Tranexamic Acid 2.5%: Helps fade dark spots and discoloration for a clearer, more even complexion Niacinamide 2.5%: Refines uneven tone and strengthens the skin barrier for a smooth, luminous finish Glutathione: A powerful antioxidant that supports brighter, healthier-looking skin Ceramide: Locks in moisture and reinforces the skin barrier to prevent dryness Hyaluronic Acid: Deeply hydrates and plumps the skin, helping to restore a soft, supple feel Cica &amp; Heartleaf: Gently calm irritation and support balanced, healthy skin — perfect for sensitive skin Ingredient Highlights Sulfate-Free Mineral Oil Free Cruelty-Free Fragrance-Free Paraben-Free Alcohol-Free Silicone-FRee",
    ingredients: "Full list of ingredients Water, Butylene Glycol, Caprylic/Capric Triglyceride, Triethylhexanoin, Methyl Trimethicone, Polyglyceryl-5 Polyricinoleate, 1,2-Hexanediol, Niacinamide, Polyglyceryl-6 Polyricinoleate, Simmondsia Chinensis (Jojoba) Seed Oil, Magnesium Sulfate, Nelumbo Nucifera Flower Water, Stearalkonium Hectorite, Polymethylsilsesquioxane, Propylene Carbonate, Ethylhexylglycerin, Adenosine, Disodium EDTA, Glycerin, Tocopherol, Helianthus Annuus (Sunflower) Seed Oil, Oryza Sativa (Rice) Bran Oil, Lupinus Albus Seed Extract, Saccharomyces/Viscum Album (Mistletoe) Ferment Extract, Hydrogenated Lecithin, Lactobacillus/Soybean Ferment Extract, Polyglyceryl-10 Stearate, Saccharomyces/Imperata Cylindrica Root Ferment Extract, Carbomer, Panthenol, Sodium Hyaluronate, Polysorbate 20, Sodium Ascorbyl Phosphate, Hydrolyzed Hyaluronic Acid, Hydrolyzed Sodium Hyaluronate, Mentha Rotundifolia Leaf Extract, Camellia Sinensis Leaf Extract, Thyme Vulgaris (Thyme) Leaf Extract, Palmitoyl Tripeptide-1, Palmitoyl Tetrapeptide-7, Acetyl Hexapeptide-8, Acetyl Tetrapeptide-3, Arginine/Lysine Polypeptide, Biotin, Copper Tripeptide-1, Dipeptide-2, Folic Acid, Hexapeptide-11, Hydroxypropyl Trimonium Hyaluronate, Malus Domestica Fruit Cell Culture Extract, Nonapeptide-1, Oligopeptide-1, Palmitoyl Hexapeptide-12, Palmitoyl Pentapeptide-4, Pyridoxine, Sodium Acetylated Hyaluronate, Tripeptide-1, Sodium Hyaluronate Crosspolymer, Cyanocobalamin, Hyaluronic Acid, Nelumbo Nucifera Leaf Extract, Pentylene Glycol, Potassium Hyaluronate, Linoleic Acid, Sodium DNA, Thiamine HCL, Fragrance.",
    
    
    reviews: []
  },
  {
    id: 9083752939756,
    brand: "MEDIPEEL",
    name: "MEDIPEEL Premium 3.0 Collagen Naite Thread Neck Cream (100ml)",
    category: "Moisturizers",
    price: 24.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/Medipeel_Collagen_Naite_Thread.png?v=1765910565",
    
    description: "An innovative peptide cream specially designed for the neck and décolleté MEDIPEEL Premium 3.0 Collagen Naite Thread Neck Cream is formulated with low-molecular-weight hydrolyzed collagen and a patented peptide ingredient from DSM in the UK to help reduce the appearance of fine lines and wrinkles. It is designed to provide a pronounced lifting effect, smoothing the skin and helping to fight skin creases. Features P acked with 97,500ppm of hydrolyzed collagen and peptides Deeply hydrates the skin from the surface to the underlying layers Defend against dryness and external irritation Filling gaps in the skin’s texture while restoring bounce Skin Concerns Dark Spots Pigmentation Uneven Skin Anti-Aging Dryness Skin Types Suitable for all skin types, including sensitive skin Made In South Korea How to use At the last stage of your basic skincare routine, spread a generous amount to the neck area. Massage gently to aid absorption. Key Ingredients Niacinamide : Refines uneven tone and h elps remove age spots. 5 Types of Peptides : I ncreases the firmness and elasticity of the skin, r educes the depth of wrinkles and prevents sagging skin. Collagen &amp; Adenosine : Locks in moisture, accelerates the regeneration of skin cells, thereby increasing firmness and elasticity and smooths out wrinkles. Hyaluronic Acid : Deeply hydrates and plumps the skin, helping to restore a soft, supple feel. Ingredient Highlights Sulfate-Free Mineral Oil-Free Paraben-Free Alcohol-Free",
    ingredients: "Full list of ingredients Water, Hydrolyzed Collagen, Glycerin, Cetearyl Alcohol, C12-15 Alkyl Benzoate, Cetyl Ethylhexanoate, Cyclohexasiloxane, 1,2-Hexanediol, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Butylene Glycol, Carbomer, Arginine, Dimethicone, Glyceryl Stearate, Polysorbate 60, Olea Europaea (Olive) Fruit Oil, Beeswax, Peg-100 Stearate, Sodium Polyacrylate, Palmitic Acid, Stearic Acid, Fragrance, Saccharomyces/Rice Ferment Filtrate, Hydrogenated Lecithin, Ethylhexylglycerin, Adenosine, Disodium Edta, Anthemis Nobilis Flower Extract, Polyglyceryl-10 Laurate, Malt Extract, Pentylene Glycol, Panthenol, Hexyldecanol, Ceramide NP, Hydrolyzed Elastin, Palmitoyl Tripeptide-5, Dipeptide Diaminobutyroyl Benzylamide Diacetate, Centella Asiatica Extract, Lavandula Angustifolia (Lavender) Extract.",
    
    
    reviews: []
  },
  {
    id: 9083752710380,
    brand: "MEDIPEEL",
    name: "MEDIPEEL Retinol Collagen Lifting Cream (50ml)",
    category: "Moisturizers",
    price: 24.95,
    image: "https://cdn.shopify.com/s/files/1/0515/4589/9157/files/MEDIPEEL_Retinol_Collagen_Lifting_Cream_50ml.png?v=1771607611",
    
    description: "A n advanced anti-aging cream that combats sagging skin with retinol and retinal The Medi-Peel Retinol Collagen Lifting Cream has a powerful anti-aging effect, smooths wrinkles, reduces the appearance of pores, increasing elasticity and firmness. This biphasic cream consists of a classic creamy texture and a light gel, allowing you to adjust the density according to your skin's needs. For oily or combination skin, add more gel, while for normal to dry skin, add more cream. This makes the product ideal for use all year round. Features Deeply moisturizes, prevents dryness Improves skin uniformity and tone Customizable cream to gel ration 6 types of encapsulated retinol and collagen Reduces wrinkles and balances sebum production Skin Concerns Pigmentation Wrinkles Dryness Anti-Aging Uneven skin Skin Types Suitable for all skin types, including sensitive skin Made In South Korea How to use Use a spatula to scoop out the capsules and gel. Adjust the ratio according to your skin condition and gently apply it to the entire face. Key Ingredients Retinolgen™ : A combination of 6 types of encapsulated retinol and collagen that work deep in the skin Hydrolyzed Collagen : Moisturizes and prevents dryness. Panthenol : A ccelerates healing, soothes and relieves irritation, and restores the integrity of the epidermis. Niacinamide : Lightens pigmentation and prevents its appearance, normalizes sebum production, reduces shine in the T-zone (forehead, nose, cheeks and chin), and increases the protective functions of the skin. Cyanocobalamin : Moisturizes, soothes, suppresses inflammation, strengthens capillaries, and helps in the treatment of acne. Ingredient Highlights Sulfate-Free Mineral Oil Free Paraben-Free Alcohol-Free Silicone-Free",
    ingredients: "Full list of ingredients Water, Glycerin, Ethylhexyl Palmitate, Cetyl Ethylhexanoate, Glycereth-26, Dipropylene Glycol, Niacinamide, Butylene Glycol, Palmitic Acid, C14-22 Alcohols, Caprylic/Capric Triglyceride, C12-20 Alkyl Glucoside, 1,2-Hexanediol, Propanediol, Retinyl Palmitate(10,000 IU/g), Retinyl Retinoate(30 ppb), Hydroxypinacolone Retinoate(10 ppb), Madecassoside, Camellia Japonica Flower Extract, Solanum Lycopersicum (Tomato) Fruit Extract, Diethylhexyl Syringylidenemalonate, Benzotriazolyl Dodecyl p-Cresol, Glucose, Panthenol, Dipotassium Glycyrrhizate, sh-Polypeptide-121(9,900 ppb), Diisopropyl Adipate, Anastatica Hierochuntica Extract, Lecithin, PPG-13-Decyltetradeceth-24, Arachis Hypogaea (Peanut) Oil, Silybin, Retinal(50 ppb), Retinol(461 ppb), BHT, Soluble Collagen(0.01 ppb), Polyglyceryl-10 Behenate/Eicosadioate, Isopropyl Lauroyl Sarcosinate, Cyanocobalamin, Caramel, Tocopherol, Pentylene Glycol, BHA, Decyl Glucoside, Polysorbate 60, Polysorbate 20, Sorbitan Stearate, Glycereth-25 PCA Isostearate, Sorbitan Isostearate, Xanthan Gum, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Glyceryl Acrylate/Acrylic Acid Copolymer, Ammonium Acryloyldimethyltaurate/VP Copolymer, Tromethamine, Stearic Acid, Potassium Sorbate, Pentaerythrityl Tetraethylhexanoate, Disodium EDTA, Hydroxyacetophenone, Caprylyl Glycol, Ethylhexylglycerin, Fragrance.",
    
    
    reviews: []
  }
];
